zowe/imperative

Jenkinsfile, jenkins/README.md, jenkins/integration_tests.sh
With a little jenkins knowhow and some pretty impressive docker image modifications, I have been able to replace the dbus_launch shell in the integration test phase with:
```groovy
sh "echo 'jenkins' | gnome-keyring-daemon --unlock"
sh "npm run test:integration"
```
**NOTE:** In testing I have seen that the `gnome-keyring-daemon --unlock` is not needed in every pipeline. I am still trying to determine why that is the case and how I can get that working in this pipeline.
For example, If this pipeline had run with the image `mikebauerca/docker-brightside` and I tried to create a bright profile, it would work without the need for unlocking. In our pipeline, however, a similar operation that happens in one of our test clis that are installed during pipeline execution will yield:
```
** …
```
=> No longer need dbus_launch

packages/imperative/__tests__/Imperative.test.ts, packages/imperative/src/Imperative.ts, packages/imperative/src/plugins/PluginManagementFacility.ts
Fixed the concern raised in issue "Config and command tree logging should be moved into trace" #1
by moving verbose messages into the 'trace' level of logging.
=> Log cmd tree at trace

gulp/DevelopmentTasks.ts
Until we fix #77, we discussed passing the build when npm audit returns a non zero exit code.  We may want to set up some automation to email failed results of npm audit
=> Don't fail build on npm audit vulnerabilities for now

packages/imperative/src/plugins/utilities/runValidatePlugin.ts
There was an issue with spaces in the path when doing the validate command. This problem could also surface when inside of an executable bundled with pkg due to how node is translated in that environment.
=> Allow space for validate

__tests__/src/TestUtil.ts, packages/rest/__tests__/client/RestClient.test.ts, packages/rest/src/client/RestClient.ts
Add expectBuffer methods to the RestClient in the 1.0.0 branch so that binary download in zowe CLI can be fixed
These methods are already present in master added in #4  but weren't ported to 1.0.0 until now
=> Add expectBuffer methods to restclient for 1.0.0 branch

Jenkinsfile
It's about time we use all this formatting that exists in the jenkinsfile. Who knew that we just were missing the mime type :cat:
=> Render emails as HTML

packages/rest/index.ts
This type is used in a method that can be overridden in the RestClient but wasn't exported until this PR
=> Export HTTPVerb from rest package

__tests__/src/packages/cmd/SyntaxValidator.integration.test.ts, packages/cmd/__tests__/CommandProcessor.test.ts, packages/cmd/src/CommandProcessor.ts
Fixed CommandProcessor.test.ts and SyntaxValidator.integration.test.ts to include commandLine in CommandProcessor constructor.
Fixed CommandProcessor.test.ts by adding 'any' to 'profArgs'.
Fixed CommandProcessor to mask password value in log file when included in a command.
Examples:  '--password abcde' is changed to '--password ****'
'--pass abcde' is changed to '--pass ****'
'--pw abcde' is changed to '--pw ****'
=> Command processor fixes

packages/io/__tests__/__snapshots__/IO.test.ts.snap, packages/io/src/IO.ts
In certain contexts such as https://github.com/zowe/zowe-cli/issues/218, writing a blank file is valid.  When this change is published and consumed from Zowe CLI, this issue will be fixed
=> Allow a blank file to be written with IO.writeFileAsync

packages/imperative/src/config/ConfigManagementFacility.ts
On a CLI's root level help, make the config group help shorter. The user can see the full help on `clinamehere config --help` 
(master only -- this isn't in LTS incremental)
=> add summary to config group for shorter top level help

package.json, packages/io/__tests__/IO.test.ts, packages/io/__tests__/__snapshots__/IO.test.ts.snap, packages/io/src/IO.ts, packages/rest/__tests__/client/AbstractRestClient.test.ts, packages/rest/src/client/AbstractRestClient.ts, packages/rest/src/client/RestClient.ts
Add new type of APIs to the Rest Client that allow the user to provide Node.js Streams rather than buffers to avoid out of memory exceptions when transferring large files. 
Fix #192
=> Add streaming APIs to Rest client

packages/cmd/__tests__/help/DefaultHelpGenerator.test.ts, packages/cmd/__tests__/help/__snapshots__/DefaultHelpGenerator.test.ts.snap, packages/cmd/src/help/DefaultHelpGenerator.ts
It turns out there are a bunch of special characters that need escaping when generating Markdown.  This fix slightly over-escapes e.g. periods only need escaping when following a number. However, it's still corrrect and without implementing half a Markdown parser I think it's tricky to do better.
=> Escape special characters when generating Markdown, fix #202

packages/cmd/__tests__/profiles/CliProfileManager.test.ts, packages/profiles/src/utils/ProfileIO.ts, packages/profiles/src/utils/__tests__/ProfileIO.test.ts
Avoids an issue where files placed in the profiles directory causes errors in the VS Code Zowe extension. Affects the loadAll API from Profile Managers. Tested by linking into the VSCode extension
=> Return only directories from ProfileIO.getAllProfileDirectories (master)

packages/rest/__tests__/session/__snapshots__/Session.test.ts.snap, packages/rest/src/session/AbstractSession.ts
REST API was failing to reuse the existing session. Discovered that the Cookie header contained a value that was truncated on the right by a single character. Removing the "- 1" in the substr() fixed the problem.
Signed-off-by: Paul Scott <paulscott@phoenixsoftware.com>
=> Prevent truncation of last character of cookie element.

package-lock.json, packages/cmd/__tests__/help/WebHelpGenerator.test.ts, packages/cmd/src/help/WebHelpGenerator.ts
Resolves #261 : zowe --help-web crashes when installed from a registry
Changed the app to get static help content from a distributed directory instead of a source directory.
=> Bug copying webhelp dist

Jenkinsfile
- Master deploys to latest
- This means that after a PR gets merged into master, a version has to be selected by one of the admins, otherwise it will fail during versioning or deployment (since it will try to push a git tag or deploy a version that already exists.
- This also means the `@daily` tag will not be updated any longer.
- Add more admins and emailList
=> Jenkins updates

packages/cmd/src/help/WebHelpGenerator.ts, packages/cmd/src/help/WebHelpManager.ts, packages/cmd/src/help/doc/IWebHelpManager.ts, packages/cmd/src/help/doc/IWebHelpPackageMetadata.ts, packages/cmd/src/help/doc/IWebHelpTreeNode.ts, web-help/docs.ts, web-help/tree.ts
* Resolves #275 by adding JSDoc to web help code in the folders `packages/cmd/src/help` and `web-help`
* Also fixes #283 ("Web help search only finds highest result in tree")
=> Add JSDoc to web help

__tests__/__integration__/cmd/__tests__/integration/cli/gen-help/Cmd.cli.gen-webhelp.example-test.integration.test.ts, packages/cmd/src/help/WebHelpGenerator.ts
* Fix #272 (Always remove WebHelp's test runtime root directory)
* Fix #297 (Before generating web help, "web-help/docs" directory should be deleted)
=> Ensure web-help/docs folder is empty before generating web help (master)

__tests__/src/packages/profiles/__snapshots__/CliProfileManager.credentials.spec.ts.snap, packages/cmd/src/profiles/CommandProfileLoader.ts, packages/imperative/src/profiles/handlers/NewDeleteProfilesHandler.ts, packages/profiles/__tests__/BasicProfileManager.load.test.ts, packages/profiles/__tests__/__snapshots__/BasicProfileManager.load.test.ts.snap, packages/profiles/src/abstract/AbstractProfileManager.ts, packages/profiles/src/doc/response/IProfileDeleted.ts
* Fixes #43 (also [zowe-cli #108](https://github.com/zowe/zowe-cli/issues/108), [zowe-cli #541](https://github.com/zowe/zowe-cli/issues/541), [zowe-cli-cics-plugin #15](https://github.com/zowe/zowe-cli-cics-plugin/issues/15) once their Imperative dependency is updated)
* When attempting to load a default profile, if it cannot be loaded, instead of "Cannot read property 'host' of undefined" the following message will be shown:
* When a profile is deleted, Imperative now checks whether it is the default profile for its type. If so the default profile name for that type is reset to `null`, so that there will be no default profile rather than a non-existent one. This results in a message like the following:
* If a user manually deletes a profile YAML file, it is still possible for their …
=> Fix unexpected behavior after default profile is deleted

packages/cmd/src/help/WebHelpGenerator.ts, web-help/dist/css/docs.css, web-help/dist/css/main.css, web-help/docs.ts
Adds a Print button at the top of the docs page for each CLI command.
Before:
After:
This makes possible a new method for generating the CLI reference PDF. In the flattened view of web help, it is now possible to print the HTML page as a PDF and a table of contents will be inserted.
=> Add Print button to web help pages

package-lock.json, packages/cmd/src/doc/profiles/parms/ICliLoadAllProfiles.ts, packages/cmd/src/doc/profiles/parms/ICliLoadProfile.ts, packages/cmd/src/profiles/CliProfileManager.ts, packages/profiles/src/abstract/AbstractProfileManager.ts, packages/profiles/src/doc/parms/ILoadAllProfiles.ts, packages/profiles/src/doc/parms/ILoadProfile.ts, packages/profiles/src/doc/parms/index.ts
This is part of the fix for the issue https://github.com/zowe/zowe-cli/issues/665. (The other part of the fix is the PR https://github.com/zowe/zowe-cli-scs-plugin/pull/7.)
* Sets "noSecure = true" during loading of all profiles in `AbstractProfileManager.delete` to check for profile dependencies. This prevents fields that may or may not be secure from being loaded unnecessarily.
* Adds `ILoadAllProfiles` type, which was referenced in a comment but not defined
* Redefines `ICliLoadAllProfiles` and `ICliLoadProfile` types to mirror the types `ILoadAllProfiles` and `ILoadProfile`, since they no longer have additional properties of their own.
=> Don't load secure profile fields when deleting profile

package-lock.json, packages/cmd/__tests__/profiles/CliProfileManager.credentials.test.ts, packages/cmd/src/profiles/CliProfileManager.ts, packages/cmd/src/types/SecureOperationFunction.ts, packages/security/__tests__/DefaultCredentialManager.test.ts, packages/security/__tests__/abstract/AbstractCredentialManager.test.ts, packages/security/src/DefaultCredentialManager.ts, packages/security/src/InvalidCredentialManager.ts, packages/security/src/abstract/AbstractCredentialManager.ts
This is part of the fix for the issue https://github.com/zowe/imperative/issues/364. (The other part of the fix is the PR https://github.com/zowe/zowe-cli-scs-plugin/pull/11.)
Adds a boolean param `optional` to methods that load credentials. If set to true, the secure field being loaded is considered optional, meaning that failure to load it will be ignored.
=> Fix error when optional secure fields in profile are missing

CHANGELOG.md, __tests__/__integration__/cmd/__tests__/integration/cli/respond/__snapshots__/Cmd.cli.respond.with-syntax-errors.test.ts.snap, __tests__/__integration__/cmd/src/cli/validate/syntax/Syntax.definition.ts, __tests__/src/packages/cmd/SyntaxValidator.integration.test.ts, __tests__/src/packages/cmd/ValidationTestCommand.ts, packages/cmd/__tests__/response/__snapshots__/CommandResponse.test.ts.snap, packages/cmd/src/syntax/SyntaxValidator.ts, packages/cmd/src/syntax/__tests__/SyntaxValidator.test.ts
Regular expressions defined for allowable values are wrapped with ^ and $ by default in order to match the whole input. Exception is when user already uses ^ or $ in definition.
In my opinion this is a breaking change, although it only affects very few cases.
See idea and discussion in zowe/zowe-cli#692
=> feat: allowable values match whole input

CHANGELOG.md, packages/rest/__tests__/client/AbstractRestClient.test.ts, packages/rest/__tests__/client/__snapshots__/AbstractRestClient.test.ts.snap, packages/rest/__tests__/session/Session.test.ts, packages/rest/__tests__/session/__snapshots__/Session.test.ts.snap, packages/rest/src/client/AbstractRestClient.ts, packages/rest/src/client/RestConstants.ts, packages/rest/src/session/AbstractSession.ts, packages/rest/src/session/doc/ISession.ts
`ISession.type` originally has these 3 value `"none" | "basic" | "token"`
I add "bearer".
However, I think `token` here should be changed into `cookie` (also `AbstractSession.TYPE_TOKEN` to `AbstractSession.TYPE_COOKIE`). But that would probably break someone who is using it.
This is my first time making changes to imperative. Open to all critics and suggestions :)
=> Add Bearer type for Session in rest

CHANGELOG.md, __tests__/__integration__/cmd/__tests__/integration/cli/profiles/__scripts__/profiles/base_and_kiwi_profile.sh, __tests__/__integration__/cmd/__tests__/integration/cli/profiles/__snapshots__/Cmd.cli.profiles.create.banana-profile.integration.test.ts.snap, __tests__/__integration__/cmd/src/imperative/config.ts, packages/cmd/__tests__/profiles/builders/__snapshots__/CompleteProfilesGroupBuilder.test.ts.snap, packages/cmd/__tests__/profiles/builders/__snapshots__/ProfilesCreateCommandBuilder.test.ts.snap, packages/cmd/src/CommandPreparer.ts, packages/cmd/src/CommandProcessor.ts, packages/constants/src/Constants.ts, packages/imperative/src/profiles/builders/ProfilesCreateCommandBuilder.ts, packages/imperative/src/profiles/handlers/CreateProfilesHandler.ts, packages/messages/src/CoreMessages.ts, packages/profiles/src/doc/parms/ISaveProfile.ts
Adds the --dd or --disable-defaults flag to the profile creation handler, allowing for the creation of profiles without their specified default values. This is vital for allowing the base profile to handle the values of these options without introducing breaking changes.
=> Add functionality to disable population of default values in profiles

CHANGELOG.md, package-lock.json, package.json, packages/rest/__tests__/session/CredsForSessCfg.test.ts
Removed mock-stdin which fails in pipeline. Used alternate approach instead.
Added tests for prompting for user name and password.
Once this PR is merged into the 'tokens' branch, the pipeline for the 'tokens' branch should once again run successfully.
=> Fix prompt tests

CHANGELOG.md, package-lock.json, package.json
This PR updates log4js because there is a fix to its FileSync appender. With the current version being pulled in (6.1.0), logging does not work when Zowe Imperative is used in a Webpacked extension. Upgrading to log4js 6.3.0 should allow logging to work when the extension uses Webpack.
The change will be used to help bring [Webpack into Zowe Explorer](https://github.com/zowe/vscode-extension-for-zowe/issues/74).
=> Update log4js version

CHANGELOG.md, package.json
Remove temporary build modifications that were used to enable zowe-cli to build with an unpublished imperative.
The token-enabled version of Zowe-CLI will not be able to build until:
- This PR is merged into the "tokens" branch
- The "tokens" branch is merged into the "master" branch
- And imperative is published to NPM.
=> Remove build hacks

CHANGELOG.md, packages/utilities/__tests__/ProcessUtils.test.ts, packages/utilities/src/ProcessUtils.ts
Fixes #322 which is related to https://github.com/zowe/zowe-cli/issues/738
Recent versions of macOS don't define the DISPLAY environment variable: https://stackoverflow.com/questions/31622295/no-x11-display-variable-was-set-on-mac
=> Don't expect DISPLAY to be defined on macOS

CHANGELOG.md, package-lock.json, packages/cmd/__tests__/profiles/CliProfileManager.test.ts, packages/cmd/src/profiles/CliProfileManager.ts
* Fixed #379 where "managed by &lt;CredentialManager&gt;" was stored in credential vault instead of the actual value. This only happened when `CliProfileManager.updateProfile` was called with a profile object and no CLI args.
`CliProfileManager.processSecureProperties` should be called only once in the `saveProfile` method. It was being called twice, in both `saveProfile` and `updateProfile`.
* Removed test that was duplicate of another test in the same suite. It is still [here](https://github.com/zowe/imperative/blob/fix-379/packages/cmd/__tests__/profiles/CliProfileManager.test.ts#L198-L199).
=> Process secure properties only once on profile update

CHANGELOG.md, __tests__/__integration__/cmd/__tests__/integration/cli/validate/__snapshots__/Cmd.cli.validate.test.ts.snap, __tests__/__integration__/cmd/src/cli/validate/syntax/Syntax.definition.ts, __tests__/src/packages/cmd/SyntaxValidator.integration.test.ts, __tests__/src/packages/cmd/ValidationTestCommand.ts, packages/cmd/src/syntax/SyntaxValidator.ts, packages/cmd/src/syntax/__tests__/SyntaxValidator.test.ts
=> Array with allowable values

CHANGELOG.md, packages/rest/__tests__/session/Session.test.ts, packages/rest/__tests__/session/__snapshots__/Session.test.ts.snap, packages/rest/src/session/AbstractSession.ts
Commit b1a0fad introduced a breaking change to AbstractSession.storeCookie() for APIs and applications generating cookie names that can't be fully known at build time. The current code assumes the "=" character separating cookie name and cookie value immediately follows the value stored in tokenType. This assumption breaks down when the server generates a cookie name starting with a fixed character string followed by an additional character string generated at run time.
This proposed change continues to support static cookie names as well as dynamically generated cookie names. Imperative's test:unit was run successfully against this change.
Dynamically generated cookie names might be used by APIs and servers that can listen for connections on multiple ports, where the port has some …
=> AbstractSession.storeCookie() support for run-time defined cookie names.

__tests__/__integration__/cmd/__tests__/integration/cli/prompting/cli.prompting.integration.test.ts, __tests__/__integration__/imperative/package.json
Temporarily disable node-pty test on Windows until https://github.com/microsoft/node-pty/issues/437 is fixed.
Also update Keytar dependency in Imperative test CLI to support Node 14.
=> Disable integration test that hangs on Windows

package-lock.json, package.json
Update opener dependency in response to GitHub Security Advisory [GHSL-2020-145: "Command injection on Windows in Opener"](https://securitylab.github.com/advisories/GHSL-2020-145-domenic-opener)
=> Update version of opener dependency to 1.5.2

CHANGELOG.md
Note to self: The changelog should not have quotes on the recent changes header.
=> Change wording on changelog for 4.8.2 release

CHANGELOG.md, packages/utilities/src/TextUtils.ts
When using `TextUtils.wordWrap()` to truncate lines, as in #444, whitespace between columns is removed. This change exposes the `trim` parameter from `wrap-ansi`, in order to prevent this behavior.
This is an optional parameter, and the default value from `wrap-ansi` is kept, so no existing code is affected.
=> Expose trim parameter within TextUtils.wordWrap()

packages/config/index.ts, packages/config/src/Config.ts, packages/config/src/ConfigSchema.ts, packages/config/src/doc/IConfig.ts, packages/imperative/src/config/cmd/init/init.definition.ts, packages/imperative/src/config/cmd/init/init.handler.ts, packages/imperative/src/config/cmd/schema/schema.handler.ts, packages/imperative/src/config/cmd/secure/secure.handler.ts, packages/imperative/src/doc/IImperativeConfig.ts, packages/profiles/src/doc/definition/IProfileProperty.ts
This PR alters `zowe config init` to generate the desired config template.
- Two profiles are created at top level: a base profile `my_base` and another profile `my_profiles` that wraps service profiles
- The name `my_profiles` can be overridden by the value of `IImperativeConfig.templateProfileName` (e.g., `lpar1` for Zowe CLI)
- Plain text profile properties with `IProfileProperty.includeInTemplate` set to true are added with their default value
- Secure profile properties with `IProfileProperty.includeInTemplate` set to true are added to the `secure` array
- Profile properties with the same value across multiple service profiles (e.g., `"host": ""`) are "hoisted" up to `my_profiles`
- Secure property values are prompted for and saved to credential vault unless the `--ci` argument is …
=> [json-config-next] Dynamically build zowe.config.json template

packages/security/src/DefaultCredentialManager.ts
As decided in a team meeting we will no longer attempt to read secure properties for the @brightside/core service which was used in the LTS-incremental branch.
Also, directly place services into allServices in the desired order. It seems simpler to follow the logic.
=> Remove LTS-incremental @brightside/core service

packages/config/__tests__/Config.test.ts, packages/config/__tests__/__snapshots__/Config.test.ts.snap, packages/config/src/Config.ts, packages/security/__tests__/DefaultCredentialManager.test.ts, packages/security/src/DefaultCredentialManager.ts
This is hopefully an easier PR to review than #478 🙂 - will try to keep them smaller
* Don't throw error in `Config.load` when secure vault fails to initialize. We can prompt for values instead.
* Fix Keytar not being found in CLI node_modules folder. Added a test for this as it was a regression since #464.
=> [json-config-next] Fixes for Config secure load

CHANGELOG.md
Adding a bit of detail to the most recent changelog entry for `allowDuplicateValues`. @liuxh0 @t1m0thyj - can you verify that I'm not misrepresenting your contribution in any way? Thanks!
=> Changelog description for v1.18.0

__tests__/src/packages/profiles/__snapshots__/CliProfileManager.credentials.spec.ts.snap, packages/config/__tests__/Config.secure.test.ts, packages/config/__tests__/Config.test.ts, packages/config/__tests__/__snapshots__/Config.test.ts.snap, packages/config/src/Config.ts, packages/config/src/doc/IConfigVault.ts, packages/imperative/__tests__/Imperative.test.ts, packages/imperative/__tests__/OverridesLoader.test.ts, packages/imperative/src/Imperative.ts, packages/imperative/src/OverridesLoader.ts, packages/imperative/src/plugins/utilities/PMFConstants.ts, packages/imperative/src/plugins/utilities/PluginIssues.ts
If new config does not exist, always fall back to the old implementation of `OverridesLoader.loadCredentialManager`. This fixes an issue where after removing the SCS override, Imperative would fail to read old profiles with plain text credentials.
=> [json-config-next] Fixes after restoring app settings and overrides

__tests__/__integration__/imperative/__tests__/__integration__/cli/auth/__scripts__/base_config_create.sh, __tests__/__integration__/imperative/__tests__/__integration__/cli/auth/__scripts__/base_profile_and_auth_login_config_global.sh, __tests__/__integration__/imperative/__tests__/__integration__/cli/auth/__scripts__/base_profile_and_auth_login_config_global_user.sh, __tests__/__integration__/imperative/__tests__/__integration__/cli/auth/__scripts__/base_profile_and_auth_login_config_local.sh, __tests__/__integration__/imperative/__tests__/__integration__/cli/auth/__scripts__/base_profile_and_auth_login_config_local_user.sh, __tests__/__integration__/imperative/__tests__/__integration__/cli/auth/__scripts__/base_profile_and_auth_login_create_config.sh, __tests__/__integration__/imperative/__tests__/__integration__/cli/auth/__scripts__/base_profile_and_auth_login_create_config_timeout.sh, __tests__/__integration__/imperative/__tests__/__integration__/cli/auth/__scripts__/base_profile_and_auth_login_show_token_config.sh, __tests__/__integration__/imperative/__tests__/__integration__/cli/config/init/cli.imperative-test-cli.config.init.integration.test.ts, __tests__/__integration__/imperative/__tests__/__integration__/cli/config/list/cli.imperative-test-cli.config.list.integration.test.ts, __tests__/__integration__/imperative/__tests__/__integration__/cli/config/profiles/cli.imperative-test-cli.config.profiles.integration.test.ts, packages/imperative/__tests__/config/cmd/init/init.handler.test.ts, packages/imperative/src/config/cmd/init/init.definition.ts, packages/imperative/src/config/cmd/init/init.handler.ts, packages/imperative/src/config/cmd/secure/secure.definition.ts, packages/imperative/src/config/cmd/set/set.definition.ts
Actually fixes #487 this time, adding the -g alias to global and changing --ci to --prompt.
=> [json-config-next] Fix #487

.gitignore, CHANGELOG.md, packages/logger/src/Logger.ts
Resolves #449
It is important for z/OSMF performance test development. This exception masks a real exception.
=> Prevent TypeError because getFileName() return null and other unexpected problems

__tests__/__integration__/imperative/__tests__/__integration__/cli/auth/__scripts__/base_profile_and_auth_login_config_global.sh, __tests__/__integration__/imperative/__tests__/__integration__/cli/auth/__scripts__/base_profile_and_auth_login_config_global_user.sh, __tests__/__integration__/imperative/__tests__/__integration__/cli/auth/__scripts__/base_profile_and_auth_login_config_local.sh, __tests__/__integration__/imperative/__tests__/__integration__/cli/auth/__scripts__/base_profile_and_auth_login_config_local_user.sh, __tests__/__integration__/imperative/__tests__/__integration__/cli/config/init/cli.imperative-test-cli.config.init.integration.test.ts, packages/config/src/ConfigUtils.ts, packages/imperative/__tests__/config/cmd/init/init.handler.test.ts, packages/imperative/__tests__/config/cmd/secure/secure.handler.test.ts, packages/imperative/__tests__/config/cmd/set/set.handler.test.ts, packages/imperative/src/auth/__tests__/BaseAuthHandler.config.test.ts, packages/imperative/src/auth/handlers/BaseAuthHandler.ts, packages/imperative/src/config/cmd/init/init.definition.ts, packages/imperative/src/config/cmd/init/init.handler.ts, packages/imperative/src/config/cmd/secure/secure.handler.ts, packages/imperative/src/config/cmd/set/set.handler.ts
* Fix `auth login` to ensure that users are always prompted before storing token when base profile already exists.
* Update `auth login`, `config secure`, and `config set X Y --secure` to show helpful error message when unable to securely save credentials.
* Update `config init` to show helpful warning message when unable to securely save credentials (shown below).
```
$ zdev config init
Warning:
Unable to securely save credentials. Skipped prompting for credentials.
Possible Solutions:
1. Reinstall Zowe CLI. On Linux systems, also make sure to install the prerequisites listed in Zowe CLI documentation.
2. Ensure Zowe CLI can access secure credential storage. Zowe CLI needs access to the OS to securely save credentials.
Saved config template to C:\dev\imperative\zowe.config.json
```
=> Fixes for tokens and secure credential storage

CHANGELOG.md, package-lock.json, package.json
There is a Denial of Service vulnerability in "marked" versions prior to 1.1.1,
the fix is available in 1.1.1 or later, see this commit which included the fix https://github.com/markedjs/marked/commit/bd4f8c464befad2b304d51e33e89e567326e62e0
This is the screenshot of "whitesource" which identified the issue:
In my package-lock.json, I also see:
```
"@zowe/imperative": {
"version": "4.10.0",
"resolved": "https://registry.npmjs.org/@zowe/imperative/-/imperative-4.10.0.tgz",
"integrity": "sha512-P1/yKhg/pnQ/0anid2EYsFh2HES5fCL1VsJ5f43xU/IjPbvRW6dZAHdSQjrs20guWdJzTMFc8IULUzkxfWrCWg==",
"requires": {
"@types/lodash-deep": "2.0.0",
"@types/yargs": "13.0.4",
"@zowe/perf-timing": "1.0.7",
"chalk": "2.4.2",
"cli-table3": "0.5.1",
"dataobject-parser": "1.2.1",
"deepmerge": "3.0.0",
"find-up": …
```
=> Update 'marked' to address security vulnerability

__tests__/__integration__/imperative/__tests__/__integration__/cli/auth/imperative.test.cli.auth.login.fruit.integration.test.ts, __tests__/__integration__/imperative/__tests__/__integration__/cli/auth/imperative.test.cli.auth.logout.fruit.integration.test.ts, __tests__/__integration__/imperative/__tests__/__integration__/cli/config/__resources__/expectedObjects.ts, __tests__/__integration__/imperative/__tests__/__integration__/cli/config/init/cli.imperative-test-cli.config.init.integration.test.ts, __tests__/__integration__/imperative/__tests__/__integration__/cli/config/list/__snapshots__/cli.imperative-test-cli.config.list.integration.test.ts.snap, __tests__/__integration__/imperative/__tests__/__integration__/cli/config/list/cli.imperative-test-cli.config.list.integration.test.ts, __tests__/__integration__/imperative/__tests__/__integration__/cli/config/secure/cli.imperative-test-cli.config.secure.integration.test.ts, __tests__/__integration__/imperative/__tests__/__integration__/cli/config/set/cli.imperative-test-cli.config.set.integration.test.ts, packages/config/__tests__/Config.test.ts, packages/config/src/Config.ts, packages/imperative/__tests__/Imperative.test.ts, packages/imperative/__tests__/OverridesLoader.test.ts, packages/imperative/__tests__/config/cmd/init/init.handler.test.ts, packages/imperative/__tests__/config/cmd/list/list.handler.test.ts, packages/imperative/__tests__/config/cmd/profiles/profiles.handler.test.ts, packages/imperative/__tests__/config/cmd/schema/schema.handler.test.ts, packages/imperative/src/Imperative.ts, packages/imperative/src/OverridesLoader.ts, packages/imperative/src/config/cmd/init/init.handler.ts, packages/imperative/src/config/cmd/list/list.handler.ts, packages/imperative/src/config/cmd/profiles/profiles.handler.ts, packages/imperative/src/config/cmd/schema/schema.handler.ts
Fixes #505. The output of "config list" command now replaces any secure values with the text `(secure value)`.
Also fixes an issue where optional Keytar dependency isn't loaded, when new config JSON file doesn't exist.
Added unit tests that were missing for "config list", "config profiles", and "config schema" command handlers.
=> Don't show secure values from config in plain text

CHANGELOG.md, packages/cmd/src/profiles/CommandProfileLoader.ts, packages/imperative/src/OverridesLoader.ts, packages/imperative/src/plugins/utilities/PMFConstants.ts, packages/profiles/src/utils/ProfileIO.ts
Fixes "Unable to perform profile I/O operations in Zowe SDKs" (#533)
=> Don't require "config" to be initialized outside of CLI-only code

CHANGELOG.md, packages/cmd/src/help/WebHelpGenerator.ts, packages/utilities/__tests__/CliUtils.test.ts
Fixes #535. The issue seems to have been caused by a breaking change in the `marked` package which was updated to fix vulnerabilities in #515.
=> Fix incorrect formatting of code blocks in web help

Jenkinsfile
Version number in changelog should be updated before we deploy a new package 😸 This fix was made in the CLI repo a while ago, but we forgot to port it to Imperative 😿
=> Update changelog in pipeline before deploy stage

CHANGELOG.md, package-lock.json, package.json, packages/cmd/src/help/WebHelpGenerator.ts
Removes marked dependency, which has a ReDoS vulnerability (https://github.com/markedjs/marked/security/advisories/GHSA-4r62-v4vq-hr96). Resolution of this vulnerability requires upgrading by a major version with breaking changes, and no Internet Explorer 11 support.
Replaces with markdown-it, which is a drop in replacement with IE11 support (and used by Visual Studio Code).
=> Use markdown-it instead of marked

packages/config/__tests__/ProfileInfo.test.ts, packages/config/src/ProfileInfo.ts, packages/config/src/doc/IProfAttrs.ts, packages/config/src/doc/IProfLoc.ts, packages/config/src/doc/IProfOpts.ts
Restores the skeleton to implement overriding values with environment variables.
This is a small change with low impact. I will merge this into profInfo-for-next at close of business Fri Mar 12, unless objections are raised.
=> Prof info restore env

packages/config/__tests__/ProfInfoErr.test.ts, packages/config/__tests__/ProfileInfo.test.ts, packages/config/src/ProfInfoErr.ts, packages/config/src/ProfileInfo.ts, packages/config/src/doc/IProfInfoErr.ts, packages/config/src/doc/IProfInfoErrParms.ts
This PR adds the ProfInfoErr class.
The way that I envision ProfInfoErr being used is:
- All errors from the ProfileInfo class will throw a ProfInfoErr.
- We will always set the errorCode property for any error thrown in ProfileInfo.
- Consumers will test for "instanceof ProfInfoErr", and then test our errorCode.
The following two items work, but we could change them based on your review opinions.
1. The errorCode property is a string. I defined a constant for each known error, and chose to use a mnemonic phase as the value.
MISSING_REQ_PROP: string = "MissingProp"
We could choose smaller strings, maybe numbers? "1", "2", "3", etc. I know that our mainframe division likes IBM-style error codes (like IEB1234), but I hate them. I do not think that they are necessary in this context, and I …
=> ProfInfoErr class into profInfo-for-next

CHANGELOG.md, __tests__/src/packages/utils/TextUtils.test.ts, __tests__/src/packages/utils/__snapshots__/TextUtils.test.ts.snap, packages/utilities/src/TextUtils.ts
Added a headers[] parameter to TextUtils.getTable(). This gives the user more control over which headers to display, and in what order. Closes #369.
As a side note, TestUtils.getTable now has 7 parameters, 5 of which are optional. It might be a good idea to move to an ITableOptions object as a parameter. I held off on this for now, as I believe this would be a breaking change, but we might want to consider this for the next major version.
Signed-off-by: mheuzey <michael.heuzey@gmail.com>
=> Added headers[] option to TextUtils.getTable()

CHANGELOG.md, packages/cmd/__tests__/response/CommandResponse.test.ts, packages/cmd/__tests__/response/__snapshots__/CommandResponse.test.ts.snap, packages/cmd/src/response/CommandResponse.ts
When calling `mProgressApi`'s `endBar()`, the contents of the `stdout` and `stderr` buffers are printed to the console. Before now, calls to `endBar()` would output duplicate data on the console because the buffers are never cleared when their contents are printed to the console. This PR rectifies this behavior by only printing a subset of the buffer that was written after the progress bar started to console.
=> Update mProgressApi and endBar to prevent output duplication

packages/imperative/src/plugins/PluginManagementFacility.ts
Fixes an issue in Imperative next branch, where plugins.json file wasn't being created at CLI launch time when team config is being used.
For now, plugins in the team config file are experimental and has not yet been adopted as a new method for managing plugins, so we always want to ensure that plugins.json exists.
This fix is necessary in order for CLI system tests to run successfully with team config.
=> [next] Always create PLUGIN_JSON file if missing

CHANGELOG.md, packages/cmd/src/CommandProcessor.ts, packages/imperative/src/OverridesLoader.ts
Fix https://github.com/zowe/zowe-cli/issues/984
This adds `Zowe` to the list of service names to read from for SCS plugin (and any others that likely do not exist).  It allows the old SCS plugin to read credentials securely stored via DefaultCredentialManager.  
I think this is technically a breaking change since `@zowe/cli` will no longer be added to [`allServices`](https://github.com/zowe/zowe-cli-scs-plugin/blob/master/src/credentials/KeytarCredentialManager.ts#L50). 
Signed-off-by: Dan Kelosky <dkelosky@gmail.com>
=> Change Override Credential Manager Service Name to Use DafaultCredentialManager Name

packages/imperative/src/OverridesLoader.ts
#589 introduced and issue where plain text profiles can no longer be read. I tested this manually, but it seemed to continue to work from residual items in my credential manger.
=> Revert Line Change from #589

CHANGELOG.md, packages/imperative/__tests__/plugins/PluginManagementFacility.test.ts, packages/imperative/src/plugins/PluginManagementFacility.ts, packages/imperative/src/plugins/cmd/install/install.handler.ts
Originally planned to merge this into master branch, but there is a breaking change as described in the changelog.
=> [next] Remove peer dep warning that no longer applies to npm@7

packages/rest/__tests__/session/ConnectionPropsForSessCfg.test.ts, packages/rest/src/session/ConnectionPropsForSessCfg.ts
Fix #639, a bug introduced in https://github.com/zowe/imperative/pull/610
Using `lodash.deepCopy` to perform a recursive deep copy on the `IHandlePromptOptions` interface attempts to deep copy the `parms: IHandlerParameters` property if present.
`IHandlerParameters` contains classes that aren't JSON serializable, resulting in strange errors when `params.response.console.prompt` is called on the deep-copied object.
The ES6 spread operator (`...`) deep copies objects with simple types like boolean/number/string, while preserving references to the original `IHandlerParameters` interface.
=> Fix "Illegal invocation" error for prompts in daemon mode

CHANGELOG.md, __tests__/src/packages/imperative/plugins/suites/ValidatePlugin.ts, packages/imperative/__tests__/plugins/cmd/validate/validate.handler.test.ts, packages/imperative/__tests__/plugins/utilities/runValidatePlugin.test.ts, packages/imperative/src/plugins/cmd/validate/validate.definition.ts, packages/imperative/src/plugins/cmd/validate/validate.handler.ts, packages/imperative/src/plugins/utilities/runValidatePlugin.ts
Allows the `validate plugins` command to return an error code and display an error if validation finds problems. Planned to enable this functionality by default in V2, but useful for upcoming scripting in V1 (i.e. extended web-help generation).
Note: Update Zowe CLI to add `--no-fail-on-error` in the post-install script validatePlugins.js once the fail-on-error option is true by default in V2.
=> Fix validate command not returning an error code

CHANGELOG.md, packages/cmd/src/help/DefaultHelpGenerator.ts, packages/cmd/src/help/WebHelpGenerator.ts
* Fix `escapeMarkdown` being called twice for positional descriptions, causing characters to be double escaped
* This was a regression introduced in #621
* Thanks to @awharn for helping to diagnose 🙂 
* Fix backslash character not being escaped, causing it to disappear at some places in web help
* Remove hack to "Remove backslash escapes from URLs" that used to be necessary to work around "marked" bug
=> Fix character escaping behavior in web help

CHANGELOG.md, __tests__/__integration__/imperative/__tests__/__integration__/cli/config/secure/cli.imperative-test-cli.config.secure.integration.test.ts, package-lock.json, packages/cmd/src/doc/profiles/definition/ICommandProfileAuthConfig.ts, packages/imperative/__tests__/config/cmd/secure/secure.handler.test.ts, packages/imperative/src/auth/handlers/BaseAuthHandler.ts, packages/imperative/src/config/cmd/secure/secure.handler.ts, packages/rest/src/session/ConnectionPropsForSessCfg.ts
Instead of prompting users directly for token value, log in to an authentication service like API ML to obtain the token.
This implements the first part of https://github.com/zowe/zowe-cli/issues/923:
> 1. Standardize on `zowe config secure`
>     > prompt for a username/password combo to get the token
=> [next] Don't prompt for token value in "config secure"

package-lock.json
TAR 6.1.8 has vulnerabilities that are detected by npm audit. Update package-lock to version 6.1.11
=> Update tar in package lock

CHANGELOG.md, __tests__/__integration__/imperative/__tests__/__integration__/cli/test/__snapshots__/cli.imperative-test-cli.test.logging.integration.test.ts.snap, __tests__/__integration__/imperative/__tests__/__integration__/cli/test/cli.imperative-test-cli.test.logging.integration.test.ts, __tests__/src/packages/imperative/plugins/suites/UsingPlugins.ts, packages/cmd/__tests__/help/WebHelpManager.test.ts, packages/cmd/src/help/WebHelpManager.ts, packages/imperative/__tests__/__snapshots__/LoggingConfigurer.test.ts.snap, packages/imperative/src/Imperative.ts, packages/logger/__tests__/LoggerConfigBuilder.test.ts, packages/logger/__tests__/__snapshots__/LoggerConfigBuilder.test.ts.snap, packages/logger/src/LoggerConfigBuilder.ts
Resolves #634. This is a breaking change.
When the environment variable `NODE_ENV=development` is set:
* Restores the old logging behavior (default log level of DEBUG)
* Disables web help caching (so that it always gets regenerated)
=> [next] Change default log level to WARN

CHANGELOG.md, __tests__/__integration__/imperative/__tests__/__integration__/cli/config/import/cli.imperative-test-cli.config.import.integration.test.ts, packages/cmd/__tests__/CommandProcessor.test.ts, packages/cmd/__tests__/__snapshots__/CommandProcessor.test.ts.snap, packages/cmd/src/CommandProcessor.ts, packages/config/__tests__/Config.secure.test.ts, packages/config/__tests__/Config.test.ts, packages/config/__tests__/__resources__/badproject.config.json, packages/config/__tests__/__snapshots__/Config.secure.test.ts.snap, packages/config/__tests__/__snapshots__/Config.test.ts.snap, packages/config/src/Config.ts, packages/config/src/doc/IConfigOpts.ts, packages/imperative/__tests__/ConfigurationLoader.test.ts, packages/imperative/__tests__/Imperative.test.ts, packages/imperative/__tests__/__model__/Sample.configuration.ts, packages/imperative/src/ConfigurationLoader.ts, packages/imperative/src/Imperative.ts, packages/imperative/src/doc/IImperativeConfig.ts
Fixes Daemon error when an incorrect zowe.config.json file is supplied.
Updates Config.load API to have a `@throws` in the JS Doc.
Fixes zowe/zowe-cli#943
Fixes zowe/zowe-cli#1190
=> Move config load into try/catch block when --dcd specified

CHANGELOG.md, __tests__/__integration__/imperative/__tests__/__integration__/cli/auth/imperative.test.cli.auth.logout.fruit.integration.test.ts, __tests__/__integration__/imperative/src/imperative.ts, __tests__/src/packages/profiles/CliProfileManager.credentials.spec.ts, packages/cmd/__tests__/CommandProcessor.test.ts, packages/cmd/__tests__/__snapshots__/CommandProcessor.test.ts.snap, packages/cmd/src/CommandProcessor.ts, packages/config/__tests__/Config.secure.test.ts, packages/config/__tests__/Config.test.ts, packages/config/src/Config.ts, packages/config/src/api/ConfigSecure.ts, packages/imperative/__tests__/Imperative.test.ts, packages/imperative/__tests__/OverridesLoader.test.ts, packages/imperative/__tests__/config/cmd/auto-init/BaseAutoInitHandler.test.ts, packages/imperative/__tests__/config/cmd/init/init.handler.test.ts, packages/imperative/src/Imperative.ts, packages/imperative/src/OverridesLoader.ts, packages/imperative/src/auth/handlers/BaseAuthHandler.ts, packages/imperative/src/config/cmd/auto-init/handlers/BaseAutoInitHandler.ts, packages/imperative/src/config/cmd/init/init.handler.ts, packages/imperative/src/config/cmd/secure/secure.handler.ts, packages/imperative/src/config/cmd/set/set.handler.ts, packages/imperative/src/doc/IImperativeConfig.ts, packages/imperative/src/plugins/PluginManagementFacility.ts
Resolves zowe/zowe-cli#1128 by changing the default CredentialManager setting in `~/.zowe/settings/imperative.json` to the package name of the host CLI (`@zowe/cli`). Supported values for CredentialManager are:
* `CredentialManager = false` - Store credentials in plain text. This was the default setting in Zowe v1 LTS and is preserved for backwards compatibility. This setting is ignored for v2 profiles which are always secure.
* `CredentialManager = '@zowe/cli'` - Store credentials using built-in credential manager. This PR makes this the default setting in Zowe v2 LTS. In v1 profiles, values of secure fields will show up as `managed by Zowe CLI`.
* `CredentialManager = 'XXX'` - Store credentials using a custom credential manager. This was only supported for v1 profiles previously, but is …
=> [next] Make credentials secure by default for v1 profiles

CHANGELOG.md, packages/config/__tests__/Config.test.ts, packages/config/src/Config.ts, packages/config/src/api/ConfigSecure.ts, packages/config/src/doc/IConfigOpts.ts
Fixes https://github.com/zowe/zowe-cli/issues/1232 by loading secure properties inside `Config.reload`
=> Fix secure properties not loaded in daemon mode

CHANGELOG.md, packages/cmd/src/doc/handler/IHandlerParameters.ts, packages/cmd/src/profiles/CommandProfiles.ts
So that calls to `IHandlerParameters.profiles.get` will be labelled as deprecated in Zowe v2.
=> [next] Deprecate v1 profiles API on IHandlerParameters

packages/imperative/__tests__/config/cmd/convert-profiles/convert-profiles.handler.test.ts, packages/imperative/src/config/cmd/convert-profiles/convert-profiles.handler.ts
⚠️ Before merging this PR, merge latest changes from #708 into this branch and ensure that all tests pass
Fix inaccurate message "Detected 1 obsolete plug-in(s)" showing when there are no CLI plug-ins installed.
=> [next] Don't show obsolete plugins that are not installed

CHANGELOG.md, packages/cmd/__tests__/yargs/YargsConfigurer.test.ts, packages/cmd/src/yargs/YargsConfigurer.ts
Fixes https://github.com/zowe/zowe-cli/issues/1081 by building `failedCommandDefinition` every time a command fails. Previously, the object was only built once when Imperative initialized, so it had a hardcoded command line of "zowe --daemon" rather than the invalid command.
=> [next] Fix inconsistent error message in daemon mode

CHANGELOG.md, packages/cmd/__tests__/CommandProcessor.test.ts, packages/cmd/__tests__/__snapshots__/CommandPreparer.test.ts.snap, packages/cmd/__tests__/__snapshots__/CommandProcessor.test.ts.snap, packages/cmd/__tests__/response/CommandResponse.test.ts, packages/cmd/src/CommandPreparer.ts, packages/cmd/src/CommandProcessor.ts, packages/cmd/src/doc/processor/ICommandProcessorParms.ts, packages/cmd/src/response/CommandResponse.ts, packages/cmd/src/yargs/AbstractCommandYargs.ts, packages/cmd/src/yargs/CommandYargs.ts, packages/constants/src/Constants.ts, packages/imperative/src/Imperative.ts, packages/imperative/src/doc/IYargsContext.ts, packages/utilities/src/doc/IDaemonResponse.ts
Implement JSON communication for data sent from client-to-server, similar to what already exists for server-to-client.
The format of the JSON body is documented in the corresponding PR https://github.com/zowe/zowe-cli/pull/1244.
The JSON object was added as a property that gets passed to CommandProcessor: `ICommandProcessorParms.daemonResponse`. This makes the `--dcd` argument unnecessary so it was removed.
=> [next] 2-way JSON communication for daemon mode

CHANGELOG.md, packages/cmd/src/yargs/CommandYargs.ts, packages/config/__tests__/ProfileCredentials.test.ts, packages/config/src/ProfileCredentials.ts, packages/security/__tests__/DefaultCredentialManager.test.ts, packages/security/src/DefaultCredentialManager.ts
* Fixed `causeErrors` missing from the Imperative log file. The default behavior of `util.inspect` is to print objects up to 2 levels deep. This works fine for a single ImperativeError object where `causeErrors` is 2 levels deep, but when there is an array of ImperativeError objects then `causeErrors` is 3 levels deep.
* Added more details to the error message displayed to the user when Keytar fails to load. Thanks @gejohnston for this suggestion 🙂
=> Improve Imperative logging for the Credential Manager

CHANGELOG.md, package-lock.json, package.json, packages/cmd/__tests__/help/WebHelpGenerator.test.ts, packages/cmd/src/help/DefaultHelpGenerator.ts, packages/cmd/src/help/WebHelpGenerator.ts
Both the [`markdown-it`](https://github.com/markdown-it/markdown-it/issues/167) and [`sanitize-html`](https://github.com/apostrophecms/sanitize-html/issues/249) packages used to generate web help should handle angle brackets correctly.
The problem seems to have been we were calling them in the wrong order - sanitizing an MD/HTML mix before passing it to `markdown-it` rather than sanitizing the output HTML resulted in some unexpected behavior.
While investigating this, I realized the amount of HTML tags being injected into the MD we feed to `markdown-it` was very small (only in the method `buildChildrenSummaryTables`). So this PR replaces those HTML tags with Markdown, removes the `html: true` option from the `markdown-it` parser, and no longer requires the `sanitize-html` package 🙂
Here …
=> Fix angle brackets escaped in web help code blocks

CHANGELOG.md, packages/cmd/__tests__/CommandProcessor.test.ts, packages/cmd/__tests__/response/CommandResponse.test.ts, packages/cmd/src/CommandProcessor.ts, packages/cmd/src/doc/handler/IChainedHandlerArgumentMapping.ts, packages/cmd/src/doc/handler/IChainedHandlerEntry.ts, packages/cmd/src/doc/handler/IHandlerParameters.ts, packages/cmd/src/doc/option/ICommandOptionAllowableValues.ts, packages/cmd/src/doc/option/ICommandOptionDefinition.ts, packages/cmd/src/doc/option/ICommandOptionValueImplications.ts, packages/cmd/src/doc/option/ICommandPositionalDefinition.ts, packages/cmd/src/doc/processor/ICommandProcessorParms.ts, packages/cmd/src/profiles/CliProfileManager.ts, packages/cmd/src/response/CommandResponse.ts, packages/cmd/src/yargs/AbstractCommandYargs.ts, packages/cmd/src/yargs/CommandYargs.ts, packages/cmd/src/yargs/GroupCommandYargs.ts, packages/cmd/src/yargs/YargsConfigurer.ts, packages/cmd/src/yargs/YargsDefiner.ts, packages/cmd/src/yargs/doc/IYargsParms.ts, packages/imperative/index.ts, packages/imperative/src/Imperative.ts, packages/imperative/src/doc/IDaemonContext.ts, packages/utilities/src/ImperativeConfig.ts
The breaking changes around using `IHandlerParameters.stdin` instead of `process.stdin` in command handlers will be documented in the corresponding CLI PR.
In addition to the documented changes in the changelog, corrected numerous formatting errors in Typedoc.
=> [next] Add stdin to handler parameters for daemon mode

CHANGELOG.md, packages/cmd/__tests__/help/AbstractHelpGenerator.test.ts, packages/cmd/__tests__/help/__snapshots__/AbstractHelpGenerator.test.ts.snap, packages/cmd/src/help/abstract/AbstractHelpGenerator.ts
=> Fix single character options rendered in help with double dash

CHANGELOG.md, packages/utilities/src/CliUtils.ts
Prevents the following from happening when you respond to a prompt with `Ctrl+C`:
```
$ znext config secure --gc
Please enter profiles.base.properties.user: Unexpected Command Error:
Please review the message and stack below.
Contact the creator of handler:
"C:\dev\zowe-next\imperative\lib\imperative\src\config\cmd\secure\secure.handler"
Message:
canceled
Stack:
Error: canceled
```
This PR handles the "read" package throwing an error with "canceled" message when a SIGINT signal is received:
https://github.com/npm/read/blob/d9385eb85b249e2d15b54a928158ff1a07f2eb47/lib/read.js#L64-L67
=> [next] Fix Ctrl+C on prompts throwing an error

packages/rest/src/session/AbstractSession.ts, packages/rest/src/session/doc/ISession.ts
Adds comments to document Node's behind the scenes behavior of using TLS_method instead of SSLv23_method. Luckily, that means we get TLS 1.3 support, and sticking with Node's default is probably for the best.
=> Document strange behind the scenes behavior for secure protocol.

CHANGELOG.md, package-lock.json, packages/rest/__tests__/client/AbstractRestClient.test.ts, packages/rest/src/client/AbstractRestClient.ts
Backports #756 from `next` to `zowe-v1-lts`
=> Fix compressed error messages returned by AbstractRestClient

CHANGELOG.md, package-lock.json, packages/rest/__tests__/client/AbstractRestClient.test.ts, packages/security/__tests__/DefaultCredentialManager.test.ts, packages/security/src/DefaultCredentialManager.ts
This is part of the fix for https://github.com/zowe/zowe-cli/issues/1314.
The remainder of the fix is https://github.com/zowe/zowe-cli/pull/1347 (will need to be ported to `next` branch).
Once both these fixes are published, it should be possible to `import { imperative } from "@zowe/cli"` and use the ProfileInfo API from the shrinkwrapped CLI package without any duplicated Imperative or Keytar dependencies.
=> Fix Keytar not found outside top-level node_modules folder

CHANGELOG.md, packages/config/__tests__/ConfigSchema.test.ts, packages/config/__tests__/ConfigUtils.test.ts, packages/config/src/ConfigSchema.ts, packages/config/src/ConfigUtils.ts, packages/imperative/src/config/cmd/secure/secure.handler.ts, packages/imperative/src/config/cmd/set/set.handler.ts
Resolves #772
I've attempted to make the new method `ConfigSchema.findPropertyType` flexible and easy to use not only in the CLI, but also in apps that use the ProfileInfo API like Zowe Explorer.
=> [next] Fix `config set` not respecting property types

CHANGELOG.md, package-lock.json, package.json, packages/console/__tests__/Console.test.ts, packages/console/src/Console.ts
The developers of Moment.js recommend not to use it anymore: https://momentjs.com/docs/#/-project-status/
Since the package had a recent vulnerability, we only used it in one place, and it was easy to replace with native JS, I've done so in this PR.
Also added a test to verify the timestamp is correct, since the original format was wrong. It was printing the month in place of minutes, and 100ths of seconds instead of 60ths.
=> Remove moment dependency

CHANGELOG.md, package.json, packages/config/__tests__/ProfileInfo.TeamConfig.test.ts, packages/config/__tests__/__resources__/ProfInfoApp_home_team_config_proj/ProfInfoApp.config.json, packages/config/src/ProfileInfo.ts, packages/config/src/api/ConfigProfiles.ts
Since there is already a feature merged into `next`, I believe I can switch the base to `master` and have this PR go out as a 5.0.1 (if needed)
I don't think the feature in next will cause any harm to the ProfileInfo APIs, so they could both be added in a 5.1.0.
Please keep in mind that ZE needs this for Zowe RC2.
=> Use base from operating layer

CHANGELOG.md, packages/imperative/__tests__/plugins/cmd/uninstall/uninstall.handler.test.ts, packages/imperative/__tests__/plugins/utilities/npm-interface/uninstall.test.ts, packages/imperative/src/plugins/cmd/uninstall/uninstall.handler.ts, packages/imperative/src/plugins/utilities/npm-interface/uninstall.ts
* Check if plugin install folder still exists after uninstall, because `npm uninstall` exit code is not very dependable
* Also fix the uninstall handler which treated the `params.arguments.plugin` as a string even though it is an array
=> Fix plugin uninstall failing when there is space in the path

.github/workflows/imperative.yml, CHANGELOG.md, package-lock.json, package.json
Same as #819 but for zowe-v1-lts
* Update `cli-table3` dependency as requested in https://github.com/zowe/imperative/issues/764#issuecomment-1122121660
* Drop Node 12 (EoL) from our CI matrix and replace it with Node 18
=> [v1] Update cli-table3 and add Node 18 to CI

CHANGELOG.md, packages/config/__tests__/ProfileInfo.TeamConfig.test.ts, packages/config/src/ProfileInfo.ts
By adding support for ENV variables, a few other issues were uncovered when `ZOWE_CLI_HOME` points to the same location as the project directory (`mHomeDir === mProjectDir`).
- OsLoc information was getting duplicated in `.knownArgs`
- `getOsLocInfo` duplicated layer information making it look like there were two of each layer available (`min: 4`, `max: 8`)
- Tests that deleted `.properties.defaults.base` from the active layer, also needed to delete the global counterpart
- There is a comment for each test that needed to be modified for this
- Tests that relied on `getOsLocInfo` needed to be updated to account for the global copy of the layer
All issues mentioned above should be resolved in this PR 😋 
---
This PR is related to https://github.com/zowe/vscode-extension-for-zowe/issues/1777
=> Default `homeDir` to `cliHome` to support environmental variables

CHANGELOG.md, packages/config/__tests__/ProfileCredentials.test.ts, packages/config/__tests__/ProfileInfo.OldProfiles.test.ts, packages/config/__tests__/ProfileInfo.TeamConfig.test.ts, packages/config/src/ConfigAutoStore.ts, packages/config/src/ProfileCredentials.ts, packages/config/src/ProfileInfo.ts, packages/config/src/doc/IConfigAutoStoreOpts.ts
Fixes a few bugs identified in the ProfileInfo API when using it in a VS Code extension.
It should be possible to call `ProfileInfo.readProfilesFromDisk` repeatedly in a VSCE with the following results:
* In an environment where no team config files exist and the `~/.zowe/profiles` directory does not exist, it should not fail.
* If team config files did not exist before, but another application created them, the config layers should be repopulated.
* If secure properties did not exist in team config before, but another application created them, they should be loaded.
=> Fix bugs in ProfileInfo API

CHANGELOG.md, packages/io/__tests__/IO.test.ts, packages/io/src/IO.ts, packages/rest/__tests__/client/AbstractRestClient.test.ts, packages/rest/src/client/AbstractRestClient.ts, packages/rest/src/client/CompressionUtils.ts
Fixes a bug in Imperative that caused zowe/zowe-cli#1458
This PR changes the default behavior of `IO.processNewlines` (when `lastByte` is null) to replace `\n` at the beginning of a string with `\r\n` on Windows. IMO this is a bug fix, not a breaking change.
=> Fix line endings not always being normalized

CHANGELOG.md, packages/imperative/__tests__/plugins/PluginManagementFacility.test.ts, packages/imperative/__tests__/plugins/utilities/npm-interface/install.test.ts, packages/imperative/src/plugins/PluginManagementFacility.ts, packages/imperative/src/plugins/utilities/npm-interface/install.ts
Fixes #859 which prevented users from installing plug-ins like `@zowe/zos-make-for-zowe-cli` and `@zowe/tasks-for-zowe-cli` which do not define new profile types in their configuration.
Also fixes an error where if global config exists and a plug-in is installed with an Imperative config that fails to load, install failed  with a cryptic error (`Cannot create property 'name' on string '{}'`) instead of reporting plug-in validation errors.
=> Fix error when installing plugin that does not define profiles

CHANGELOG.md, packages/imperative/src/config/cmd/set/set.definition.ts
Included examples for setting default profiles in zowe config set.
Linked to [#1428](https://github.com/zowe/zowe-cli/issues/1428)
=> Introduced examples for setting default profiles in Examples section

CHANGELOG.md, package.json
Added web-diff template dir to the files sections of package.json to include the files in the registry package. in order to fix the error defined here: https://github.com/zowe/zowe-cli/pull/1460#issuecomment-1215161336
Signed-off-by: sarthakjdev <jsarthak448@gmail.com>
=> fix: added web-diff template directory in files section of package.json

CHANGELOG.md, package-lock.json, package.json, packages/config/__tests__/ProfileInfo.TeamConfig.test.ts, packages/config/__tests__/__resources__/ProfInfoApp_large_team_config_proj/ProfInfoApp.config.json, packages/config/src/Config.ts, packages/config/src/ProfileInfo.ts, packages/config/src/api/ConfigProfiles.ts, packages/config/src/doc/IConfigMergeOpts.ts
Related to zowe/vscode-extension-for-zowe#1911
**Performance Comparison**
| ProfileInfo method | Time Before (ms) | Time After (ms) |
| --- | --- | --- |
| readProfilesFromDisk | 61.0 | 44.2 |
| getDefaultProfile | 49.9 | 4.8 |
| mergeArgsForProfile | 203.4 | 12.8 |
The most significant improvement is in `mergeArgsForProfile`, since some apps like Zowe Explorer call it for every profile in the team config. The time to merge args for 100 z/OSMF profiles used to be around 20s and has been reduced by over 10x.
**Summary of Changes**
* Refactors the Config and ProfileInfo APIs so that they clone JSONC objects as little as possible. I discovered that cloning a JSONC object with `JSONC.parse(JSONC.stringify(obj))` is very slow, so it should be done sparingly except when needed to prevent …
=> Improve performance of ProfileInfo API to load large team config files

.github/workflows/imperative.yml, packages/config/__tests__/ProfileInfo.TeamConfig.test.ts
⚠️ Do not merge until all builds pass. It seems that Ubuntu runners are still using Node 16.16 which doesn't include the fix.
Revert Node.js version lockdown now that the npm@8.11 bug has been fixed.
Also don't time the reading of profiles from disk in unit test. Since I/O performance may vary across GHA runners, this test was occasionally failing.
=> Revert Node lockdown in workflows

CHANGELOG.md, __tests__/__integration__/imperative/__tests__/__integration__/api/env/__snapshots__/EnvironmentalVariableSettings.integration.test.ts.snap, packages/imperative/__tests__/env/EnvironmentalVariableSettings.test.ts, packages/imperative/__tests__/plugins/utilities/PMFConstants.test.ts, packages/imperative/src/doc/IImperativeEnvironmentalVariableSettings.ts, packages/imperative/src/env/EnvironmentalVariableSettings.ts, packages/imperative/src/plugins/utilities/PMFConstants.ts
This is the Imperative part of the enhancement requested in https://github.com/zowe/zowe-cli/issues/1483
=> Add environment variable to override plugins dir

packages/cmd/src/profiles/CliProfileManager.ts, packages/cmd/src/response/CommandResponse.ts
Backport the code smell fixes to V1 LTS
=> [Backport] Fix code smells

CHANGELOG.md, packages/config/__tests__/ProfileInfo.TeamConfig.test.ts, packages/config/__tests__/__resources__/ProfInfoApp_nested_team_config_proj/ProfInfoApp.config.json, packages/config/__tests__/__resources__/ProfInfoApp_nested_team_config_proj/ProfInfoApp.schema.json, packages/config/src/ProfileInfo.ts
=> Prevent secure properties lookup on a global-layer base profile that doesn't exits

CHANGELOG.md, packages/config/__tests__/Config.test.ts, packages/config/src/Config.ts
Resolves #883 
This allows Zowe Explorer to avoid loading project config profiles when there is no workspace open in VS Code:
`profileInfo.readProfilesFromDisk({ homeDir: "~/.zowe", projectDir: workspaceRoot ?? "" })`
=> Skip loading project config layers when project directory is an empty string

.github/workflows/imperative.yml, package-lock.json
Updates the Imperative CI workflow to use latest versions of Octorelease actions to match Zowe CLI (https://github.com/zowe/zowe-cli/pull/1527).
Also updated the package lock file, which should fix #892.
=> Update workflow to use new Octorelease versions

.github/workflows/audit.yml, .github/workflows/changelog.yml, .github/workflows/imperative.yml, .github/workflows/linter.yml, CHANGELOG.md, package-lock.json, package.json, packages/imperative/__tests__/plugins/cmd/install/install.handler.test.ts, packages/imperative/__tests__/plugins/cmd/uninstall/uninstall.handler.test.ts, packages/imperative/__tests__/plugins/cmd/update/update.handler.test.ts, packages/imperative/__tests__/plugins/utilities/npm-interface/install.test.ts, packages/imperative/__tests__/plugins/utilities/npm-interface/uninstall.test.ts, packages/imperative/__tests__/plugins/utilities/npm-interface/update.test.ts, packages/imperative/__tests__/plugins/utilities/runValidatePlugin.test.ts, packages/imperative/src/plugins/utilities/NpmFunctions.ts, packages/imperative/src/plugins/utilities/npm-interface/uninstall.ts, packages/imperative/src/plugins/utilities/runValidatePlugin.ts
Execute NPM directly in several Plugin interfaces.
Replace execSync with spawnSync.
Update tests to deal with this change.
=> Be more specific about NPM execution

CHANGELOG.md, packages/imperative/src/plugins/cmd/install/install.definition.ts, packages/imperative/src/plugins/cmd/update/update.definition.ts, packages/imperative/src/plugins/utilities/NpmFunctions.ts
Prepare for breaking change in NPM 9 where `npm adduser` does not login to registries anymore (replaced with `npm login`)
Note that users will need to run a separate NPM command if they are using NPM 9 to create a user on their registry.
=> Change the command from adduser to login

CHANGELOG.md, packages/cmd/__tests__/CommandPreparer.test.ts, packages/cmd/src/CommandPreparer.ts
Implements #868:
- Added null/undefined check for provided options in a command definition
- Replaced references to isNullOrUndefined in CommandPreparer.ts w/ standard checks
(`value === null || value === undefined`)
=> null/undefined check for command def. options

packages/cmd/src/help/WebHelpGenerator.ts, packages/imperative/src/config/cmd/report-env/EnvQuery.ts
When reviewing, please verify that the updated regexes should behave the same as the old ones 🙂 
* WebHelpGenerator - searches for code blocks formatted like this: `<code>$ zowe ...</code>`
* EnvQuery: searches for lines of interest in the output of `npm config list`
These changes make SonarCloud happy (fixes [S5852](https://sonarcloud.io/organizations/zowe/rules?open=typescript%3AS5852&rule_key=typescript%3AS5852)), but are not user-facing so should not require a changelog.
=> Optimize slow regexes detected by SonarCloud

packages/imperative/src/config/cmd/report-env/EnvQuery.ts
Follow up to #909. After discussing with @gejohnston, it seemed the new regex had some undesirable change in behavior.
For example, if I had the following npm config:
```
; @zowe:registry=https://registry.npmjs.org
@zowe:registry=https://zowe.jfrog.io/zowe/api/npm/npm-local-release/
```
The "; " characters would have been stripped off in the output of `zowe config report-env`, making it unclear which line is uncommented and has priority.
=> Further optimization for EnvQuery regex

CHANGELOG.md, packages/config/__tests__/ProfileInfo.OldProfiles.test.ts, packages/config/__tests__/ProfileInfo.TeamConfig.test.ts, packages/config/__tests__/__resources__/ProfInfoApp_home/profiles/missing/missing_meta.yaml, packages/config/src/ProfileInfo.ts
=> Fix failure to load schema when there is no profile of that type

CHANGELOG.md, __tests__/src/packages/imperative/plugins/suites/ValidatePlugin.ts, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/index.d.ts, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/index.js, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/index.js.map, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/cmd/bar/bar.handler.d.ts, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/cmd/bar/bar.handler.js, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/cmd/bar/bar.handler.js.map, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/cmd/foo/foo.handler.d.ts, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/cmd/foo/foo.handler.js, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/cmd/foo/foo.handler.js.map, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/healthCheck.handler.d.ts, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/healthCheck.handler.js, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/healthCheck.handler.js.map, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/index.d.ts, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/index.js, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/index.js.map, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/package.json, __tests__/src/packages/imperative/plugins/test_plugins/error_plugins/definition_bad_chained_handler/dummy.handler.js, __tests__/src/packages/imperative/plugins/test_plugins/error_plugins/definition_bad_chained_handler/package.json, __tests__/src/packages/imperative/plugins/test_plugins/error_plugins/definition_empty_chained_handler/dummy.handler.js, __tests__/src/packages/imperative/plugins/test_plugins/error_plugins/definition_empty_chained_handler/package.json, __tests__/src/packages/imperative/plugins/test_plugins/error_plugins/definition_missing_chained_handler/dummy.handler.js, __tests__/src/packages/imperative/plugins/test_plugins/error_plugins/definition_missing_chained_handler/package.json, packages/imperative/__tests__/plugins/PluginManagementFacility.test.ts, packages/imperative/src/plugins/PluginManagementFacility.ts
Fixes #320 
Updates plugin validation logic to fix a situation where plugin commands with chained command handlers would fail plugin validation.
=> Fix plugin validation error for chained handlers

CHANGELOG.md, packages/io/__tests__/IO.test.ts, packages/io/src/IO.ts
Fixes the `console.error` call being skipped in this example due to uncatchable errors:
```
try {
await IO.writeFileAsync("nonExistentFolder/newFile", "Hello world");
} catch (err) {
console.error(`Caught exception: ${err}`);
}
```
Thanks to @zFernand0 for suggesting using `process.nextTick` in unit tests to verify the fix.
=> Fix IO.writeFileAsync method throwing errors badly

.github/workflows/audit.yml, .github/workflows/changelog.yml, .github/workflows/imperative.yml, .github/workflows/linter.yml, .github/workflows/sonar.yml, .npmrc, __tests__/src/TestUtil.ts, scripts/sampleCliTool.js
ℹ️ Note:
- This branch was created from the `v5.7.7` tag.
- This should allow us to publish directly from this branch if we don't want to release any new enhancements for Zowe v2.6.1
---
Once we publish (if we decide to do so) we can rebase the branch with master instead of the v5.7.7 tag
---
UPDATE:
No need to publish a new version of imperative.
**TODO**
- ~`[]`  label as release-current~
=> fix: Update build/test scripts to be compatible with npm@9

CHANGELOG.md, packages/config/__tests__/ProfileCredentials.test.ts, packages/config/src/ProfileCredentials.ts, packages/config/src/ProfileInfo.ts, packages/config/src/doc/IProfOpts.ts, packages/security/index.ts
Resolves https://github.com/zowe/zowe-cli/issues/1632
The `credMgrOverride` property enables consumers of the ProfileInfo API like Zowe Explorer to override just Keytar:
```
const profInfo = new imperative.ProfileInfo("zowe", {
credMgrOverride: ProfileCredentials.defaultCredMgrWithKeytar(() => __webpack_require__("keytar")),
});
```
Or the entire credential manager (pending https://github.com/zowe/zowe-cli-secrets-for-kubernetes/issues/8):
```
import { K8sCredentialManager } from "@zowe/secrets-for-kubernetes-for-zowe-cli";
const profInfo = new imperative.ProfileInfo("zowe", {
credMgrOverride: {
service: "Secrets for Kubernetes",
Manager: K8sCredentialManager
},
});
```
See [this ZE branch](https://github.com/zowe/vscode-extension-for-zowe/compare/test/k8s-credmgr-override) for an example …
=> Support credential manager override in ProfileInfo API

CHANGELOG.md, packages/cmd/__tests__/response/CommandResponse.test.ts, packages/imperative/__tests__/handlers/DefaultRootCommandHandler.test.ts, packages/utilities/__tests__/TextUtils.test.ts, packages/utilities/src/TextUtils.ts
Makes a small change to allow for color support in daemon mode by skipping the check for a TTY interface and enabling FORCE_COLOR to set the color level in `chalk`.
=> Make changes to support color in daemon mode

CHANGELOG.md, packages/imperative/__tests__/config/cmd/list/list.handler.test.ts, packages/imperative/src/config/cmd/list/list.handler.ts
Fixes a logic error that causes unwanted behavior when both a positional and `--locations` are passed into the `zowe config list` command.
Using the latest CLI, try the command described above with a configuration file. Link this branch of Imperative to the CLI, attempt a command as described above with a configuration file. Observe that the undesired behavior no longer occurs.
=> Fix logic error in config list command

CHANGELOG.md, packages/imperative/__tests__/DefinitionTreeResolver.test.ts, packages/imperative/src/DefinitionTreeResolver.ts
Checks for nulls in the DefinitionTreeResolver to fix scans.
N/A
**Additional Comments**
=> Check for nulls in the Definition Tree Resolver

CHANGELOG.md, packages/imperative/__tests__/DefinitionTreeResolver.test.ts, packages/imperative/src/DefinitionTreeResolver.ts
Implements #990 in V1 LTS
N/A
**Additional Comments**
=> Introduce fixes v1

CHANGELOG.md, packages/utilities/src/NextVerFeatures.ts
I originally thought that using ImperativeConfig.instance.envVariablePrefix was the appropriate way to get the prefix for the ZOWE_V3_ERR_FORMAT variable. However, many API system tests do *NOT* call imperative.init(). We would be required to create very many mocks in our system tests to make such tests run successfully. That situation brought to light the possibility that any external app which uses a NextVerFeatures function, but which does not first call imperative.init(), will fail with some form of error.
This PR replaces the need for imperative.init() by simply placing the literal string "ZOWE" within the NextVerFeatures module for use as the prefix for environment variables.
There is no new functionality in this PR. As long as automated tests run …
=> Use literal "ZOWE" as env prefix for NextVerFeatures

CHANGELOG.md, __tests__/__integration__/imperative/__tests__/__integration__/cli/auth/imperative.test.cli.auth.logout.fruit.integration.test.ts, packages/config/__tests__/Config.api.test.ts, packages/config/__tests__/ConfigAutoStore.test.ts, packages/config/src/ConfigAutoStore.ts, packages/config/src/ConfigConstants.ts, packages/config/src/ProfileInfo.ts, packages/config/src/api/ConfigLayers.ts, packages/config/src/api/ConfigProfiles.ts, packages/config/src/api/ConfigSecure.ts, packages/expect/__tests__/ImperativeExpect.test.ts, packages/expect/src/ImperativeExpect.ts, packages/imperative/__tests__/config/cmd/auto-init/BaseAutoInitHandler.test.ts, packages/imperative/__tests__/config/cmd/auto-init/__data__/FakeAutoInitHandler.ts, packages/imperative/__tests__/config/cmd/init/init.handler.test.ts, packages/imperative/__tests__/config/cmd/secure/secure.handler.test.ts, packages/imperative/src/auth/__tests__/BaseAuthHandler.config.test.ts, packages/imperative/src/auth/__tests__/BaseAuthHandler.test.ts, packages/imperative/src/auth/__tests__/__resources__/auth.config.json, packages/imperative/src/auth/handlers/BaseAuthHandler.ts, packages/imperative/src/config/cmd/auto-init/handlers/BaseAutoInitHandler.ts, packages/imperative/src/config/cmd/init/init.handler.ts, packages/imperative/src/config/cmd/secure/secure.handler.ts, packages/rest/src/client/AbstractRestClient.ts, packages/rest/src/session/ConnectionPropsForSessCfg.ts
- resolves #979
- added a new `add ImperativeExpect.toMatchRegExp` method
- prevented multiple `logout` operations from failing due to not having a token available 
- allowed `autoStore` for dynamic APIML token types
- ~allowed `logout` operation to remove token type and/or token value when either is not specified in the config file~
- this cannot be done because it conflicts with the ability to logout a token different than the one stored in the vault
- added utility method: `getProfileNameFromPath` to help with nested token authentication
- added support for multiple token authentication processes in a single `config secure` command
- added an entry to the `console.log` to inform which profile credentials are being prompted for
- prevented `auto-init` from performing …
=> Handle new APIML unique cookie identifier

CHANGELOG.md, packages/config/__tests__/ProfileInfo.TeamConfig.test.ts, packages/config/__tests__/__resources__/ProfInfoApp_team_config_proj/ProfInfoApp.config.json, packages/config/src/ProfileInfo.ts, packages/config/src/doc/IProfArgAttrs.ts
=> ProfileInfo: Identify non-schema properties in the `mergedArgs`

__tests__/__integration__/imperative/package.json, package-lock.json, package.json
This PR bumps the secrets SDK to 7.18.0
=> chore: Bump secrets SDK to 7.18.0

CHANGELOG.md, packages/config/__tests__/ProfileInfo.TeamConfig.test.ts, packages/config/src/ProfileInfo.ts
Fixes #1008 so that user and password takes precedence over tokenValue when both are defined in profile properties.
1. Create a team config file that has both user/password and tokenValue defined (such as the example provided in the linked issue).
2. Call `ProfileInfo.createSession` (using a test script like the one below) and verify that only user/password are present in the session.
```javascript
const { ProfileInfo } = require("@zowe/imperative");
(async () => {
// Load connection info from default z/OSMF profile
const profInfo = new ProfileInfo("zowe");
await profInfo.readProfilesFromDisk();
const zosmfProfAttrs = profInfo.getDefaultProfile("zosmf");
const zosmfMergedArgs = profInfo.mergeArgsForProfile(zosmfProfAttrs, { getSecureVals: true });
const …
```
=> Fix merging of profile properties in `ProfileInfo.createSession`

CHANGELOG.md, packages/rest/__tests__/client/AbstractRestClient.test.ts, packages/rest/src/client/AbstractRestClient.ts
Fixes the abstract rest client's implementation of normalization
**Additional Comments**
=> Fix abstract rest client (2 of 4) (Imperative V1)
