zowe/imperative

__mocks__/yargs.ts, __tests__/src/TestUtil.ts, packages/rest/__tests__/client/RestClient.test.ts, packages/rest/src/client/RestClient.ts
Add methods to return buffers from rest client for APIs returning binary data
=> Add 'expectBuffer' group of methods to RestClient.ts

README.md, package.json
I added installation instructions and tweaked a few of the introductory sentences.
=> README updates - add install instructions  fix #15

packages/imperative/src/plugins/utilities/npm-interface/update.ts
=> Removing outdated comment

package.json
Forgot to do this in the expectBuffer PR
Signed-off-by: ChrisBoehmCA <Christopher.Boehm@broadcom.com>
=> update imperative version in package.json in 1.0.0 branch for expectBuffer changes

package.json
=> fix repository in package.json

__tests__/src/packages/profiles/CliProfileManager.credentials.spec.ts, packages/cmd/src/profiles/CliProfileManager.ts, packages/profiles/src/validation/api/ProfileValidator.ts
Fix bug introduced in  #120 
Fix #147
=> Fix issue where profile name is not displayed when a secure field fails to save

Jenkinsfile, package.json
- Enhance pipeline to implement CI for all intended release branches
Successful run: https://wash.zowe.org:8443/blue/organizations/jenkins/imperative/detail/master/216/pipeline/
=> Update jenkinsfile to accommodate all deployment

.gitignore, Jenkinsfile, __tests__/__integration__/cmd/package-lock.json, __tests__/__integration__/hello_world/package-lock.json, __tests__/src/example_clis/with_profiles/AutoGeneratedProfileCommands.spec.ts, __tests__/src/example_clis/with_profiles/ProfileExampleConfiguration.ts, __tests__/src/packages/cmd/SyntaxValidator.integration.test.ts, __tests__/src/packages/profiles/CliProfileManager.credentials.spec.ts, package-lock.json, package.json, packages/cmd/__tests__/CommandProcessor.test.ts, packages/cmd/__tests__/profiles/CliProfileManager.credentials.test.ts, packages/cmd/__tests__/profiles/CliProfileManager.test.ts, packages/cmd/__tests__/profiles/builders/__snapshots__/CompleteProfilesGroupBuilder.test.ts.snap, packages/cmd/__tests__/profiles/builders/__snapshots__/ProfilesDeleteCommandBuilder.test.ts.snap, packages/cmd/__tests__/profiles/builders/__snapshots__/ProfilesListCommandBuilder.test.ts.snap, packages/cmd/__tests__/profiles/builders/__snapshots__/ProfilesSetCommandBuilder.test.ts.snap, packages/cmd/src/CommandProcessor.ts, packages/cmd/src/doc/profiles/definition/ICommandProfileTypeConfiguration.ts, packages/cmd/src/profiles/CliProfileManager.ts, packages/imperative/src/profiles/builders/ProfilesDeleteCommandBuilder.ts, packages/imperative/src/profiles/builders/ProfilesListCommandBuilder.ts, packages/imperative/src/profiles/builders/ProfilesSetCommandBuilder.ts, packages/imperative/src/profiles/builders/ProfilesUpdateCommandBuilder.ts, packages/messages/src/CoreMessages.ts, packages/profiles/src/validation/api/ProfileValidator.ts
This will trigger a build that will publish a @beta with a `-beta.#` pre-release string
=> Merge master into beta

Jenkinsfile
Also prevent master from publishing another daily version
=> Fix all other master-only assumptions

Jenkinsfile
=> Fix all other master-only assumptions [ci skip]

packages/rest/src/client/AbstractRestClient.ts
***DO NOT MERGE YET***
The purpose of this PR is to ensure that this random failure does not occur again in the future.
Please do not merge this PR right away as it could serve as a test in enough itself.
This is an attempt to address #136
=> Posix.Normalize the output path

.gitignore, packages/cmd/src/CommandProcessor.ts
Based on discussion, mask user id value from log.
=> User masking

package.json
=> Remove unused @types/lodash

Jenkinsfile, package.json
Address deploy problems by using the new functionality on the shared library (i.e. scopes)
=> Fix deploy

packages/imperative/__tests__/plugins/cmd/list/list.handler.test.ts, packages/imperative/src/plugins/cmd/list/list.handler.ts
=> output plugins object in data field on plugins list --rfj

Jenkinsfile
Jenkinsfile wasn't using the new library. Copied the file from master, changing @zowe to @brightside since this is LTS incremental
=> Update jenkinsfile in LTS incremental

package.json
Accidentally bumped typescript version. Reverting it now
=> revert typescript version

__tests__/src/packages/cmd/SyntaxValidator.integration.test.ts, packages/cmd/src/syntax/SyntaxValidator.ts
=> Fix #54 where 0 could not be specified for positionals (lts-incremental)

__tests__/src/packages/cmd/SyntaxValidator.integration.test.ts, packages/cmd/src/syntax/SyntaxValidator.ts
=> Fix #54 where 0 could not be specified for positionals

package.json, packages/io/__tests__/IO.test.ts, packages/io/__tests__/__snapshots__/IO.test.ts.snap, packages/io/src/IO.ts, packages/rest/__tests__/client/AbstractRestClient.test.ts, packages/rest/src/client/AbstractRestClient.ts, packages/rest/src/client/RestClient.ts
Same changes as #199 
Fix #192
=> Introduce streaming rest client methods (lts-incremental)

Jenkinsfile
Signed-off-by: ChrisBoehmCA <Christopher.Boehm@broadcom.com>
=> Move vulnerability check later in the build so that tests can still run (lts incremental)

packages/cmd/src/help/DefaultHelpGenerator.ts
Fix some of the issues in https://github.com/zowe/zowe-cli/issues/326
=> Markdown help generator fixes

packages/cmd/src/help/DefaultHelpGenerator.ts
Same changes as #208 for lts-incremental
=> Markdown fixes  lts-incremental

packages/cmd/src/profiles/CliProfileManager.ts
=> Log secure load cause errors (master)

packages/imperative/src/config/cmd/get/get.definition.ts, packages/imperative/src/config/cmd/list/list.definition.ts, packages/imperative/src/config/cmd/reset/reset.definition.ts, packages/imperative/src/config/cmd/set/set.definition.ts, packages/imperative/src/plugins/cmd/list/list.definition.ts, packages/imperative/src/plugins/cmd/update/update.definition.ts
=> Make format of command summaries consistent (master)

packages/imperative/src/config/cmd/reset/reset.definition.ts, packages/imperative/src/config/cmd/set/set.definition.ts, packages/imperative/src/plugins/cmd/list/list.definition.ts, packages/imperative/src/plugins/cmd/update/update.definition.ts
Same as #222 but for `lts-incremental`
=> Make formatting of command summaries consistent (lts-incremental)

gulp/SampleCliAndPlugin.ts, package.json, packages/error/src/ImperativeError.ts, tsconfig.json
Updated some package.json dependencies/devDependencies to more current version to match lts-incremental.  Also added some jest values. This arose due to errors running jest in Intellij
=> Package.json update

package-lock.json, package.json
=> Complete lockdown and remove shrinkwrap from package

package-lock.json, package.json
=> Remove shrinkwrap and lockdown package

imperative.ppf
Signed-off-by: Yan Li <raymondyanli@gmail.com>
@MarkAckert Please review the AppScan configure file.
cc @jackjia-ibm
=> adding AppScan config file

README.md
Fixes #242
I think it works to just link to the node-gyp readme for these; chatted with @tucker01.
=> Update software req for Python/C++ Compiler

.codecov.yml, Jenkinsfile, README.md
Signed-off-by: Jessielaine Punongbayan <jessielaine.punongbayan@broadcom.com>
=> Add Codecov Settings

package-lock.json
Maybe we can clean the package-lock even further?
=> further clean-up package-lock?

packages/io/__tests__/IO.test.ts, packages/io/__tests__/__snapshots__/IO.test.ts.snap, packages/io/src/IO.ts
Signed-off-by: Dan Kelosky <dkelosky@gmail.com>
=> Fix https://github.com/zowe/zowe-cli/issues/473

gulp/DevelopmentTasks.ts, packages/cmd/src/help/WebHelpGenerator.ts, packages/cmd/src/help/WebHelpManager.ts
* Fixes #273 by postponing import of web help dependencies until they are needed
* Fixes #277 by forcing browserify to concatenate CSS in required order
=> Fix web help issues

.gitignore, gulp/DevelopmentTasks.ts, packages/cmd/src/help/WebHelpGenerator.ts, packages/cmd/src/help/WebHelpManager.ts
Same as #278, but for lts-incremental branch
=> Fix web help issues (lts-incremental)

.gitignore, gulp/DevelopmentTasks.ts, packages/cmd/src/help/WebHelpGenerator.ts, packages/cmd/src/help/WebHelpManager.ts, packages/cmd/src/help/doc/IWebHelpManager.ts, packages/cmd/src/help/doc/IWebHelpPackageMetadata.ts, packages/cmd/src/help/doc/IWebHelpTreeNode.ts, web-help/docs.ts, web-help/tree.ts
Same as #284, but for lts-incremental branch
#291 should be merged first
=> Add JSDoc to web help (lts-incremental)

packages/cmd/src/help/WebHelpGenerator.ts
Same as #298, but for lts-incremental branch
=> Ensure web-help/docs folder is empty before generating web help (lts-incremental)

.gitignore, package-lock.json, package.json, typedoc.json
=> Add typedoc and fix vulnerability

packages/imperative/__tests__/plugins/utilities/npm-interface/uninstall.test.ts, packages/imperative/src/plugins/utilities/NpmFunctions.ts, packages/imperative/src/plugins/utilities/npm-interface/uninstall.ts
=> Remove surrounding spaces from npmCmd

packages/cmd/src/CommandProcessor.ts
=> Allow setting profile via environmental variable -- fix #310

Jenkinsfile, sonar-project.properties
Signed-off-by: Jack (T.) Jia <jack-tiefeng.jia@ibm.com>
As part of https://github.com/zowe/zowe-install-packaging/issues/832. There will be a similar PR to lts-incremental.
We will shutdown SonarQube on jayne.zowe.org soon.
=> Switch to SonarCloud

package-lock.json, package.json, packages/cmd/src/help/WebHelpGenerator.ts
* Fixes #319 
* Fixes #324 
* Fixes #325 
* Fixes #335
=> Fix several formatting issues in web help HTML

.npmrc, Jenkinsfile, package-lock.json, package.json
Signed-off-by: Jack (T.) Jia <jack-tiefeng.jia@ibm.com>
Part of https://github.com/zowe/zowe-install-packaging/issues/875
=> switch to zowe artifactory

packages/io/src/IO.ts, packages/rest/index.ts, packages/rest/src/session/AbstractSession.ts
=> Resolved the type of symlink

Jenkinsfile
=> Add changelog automation

CHANGELOG.md, packages/imperative/src/plugins/cmd/list/list.handler.ts
fixes #354 
Signed-off-by: mheuzey <michael.heuzey@gmail.com>
=> fixed alignment

Jenkinsfile
=> Remove lines parameter for changelog stages in pipeline

CHANGELOG.md, package-lock.json, package.json
Fixes https://www.npmjs.com/advisories/1500
=> Update yargs package

CHANGELOG.md, packages/cmd/__tests__/profiles/CliProfileManager.credentials.test.ts, packages/cmd/src/profiles/CliProfileManager.ts
=> Fix optional secure fields not deleted when overwriting a profile

__tests__/__integration__/cmd/__tests__/integration/cli/auth/Cmd.cli.auth.login.fruit.integration.test.ts, __tests__/__integration__/cmd/__tests__/integration/cli/root/__snapshots__/Cmd.cli.root.test.ts.snap, package-lock.json, package.json, packages/cmd/src/doc/profiles/definition/ICommandProfileAuthCommand.ts, packages/imperative/src/Imperative.ts, packages/imperative/src/auth/__tests__/CompleteAuthGroupBuilder.test.ts, packages/imperative/src/auth/__tests__/__snapshots__/CompleteAuthGroupBuilder.test.ts.snap, packages/imperative/src/auth/builders/AuthLoginCommandBuilder.ts, packages/imperative/src/auth/builders/AuthLogoutCommandBuilder.ts, packages/imperative/src/auth/builders/CompleteAuthGroupBuilder.ts, packages/imperative/src/auth/handlers/BaseAuthHandler.ts, packages/imperative/src/doc/IImperativeAuthGroupConfig.ts, packages/imperative/src/doc/IImperativeConfig.ts, packages/messages/src/CoreMessages.ts, packages/rest/__tests__/session/ConnectionPropsForSessCfg.test.ts, packages/rest/index.ts, packages/rest/src/session/ConnectionPropsForSessCfg.ts, packages/rest/src/session/SessConstants.ts, tslint-packages.json, tslint.json
Implement the UX changes for tokens.
Update tests and snapshots accordingly.
=> Implement UX changes for tokens

CHANGELOG.md, packages/rest/__tests__/session/ConnectionPropsForSessCfg.test.ts, packages/rest/src/session/ConnectionPropsForSessCfg.ts
=> Don't load token value into Session object if user or password are supplied

CHANGELOG.md, packages/cmd/__tests__/CommandProcessor.test.ts, packages/cmd/src/CommandProcessor.ts, packages/logger/__tests__/LoggerUtils.test.ts, packages/logger/src/LoggerUtils.ts, packages/rest/__tests__/session/ConnectionPropsForSessCfg.test.ts, packages/rest/src/session/ConnectionPropsForSessCfg.ts
=> Hide sensitive session properties in log file

CHANGELOG.md, packages/rest/src/session/doc/ISession.ts
=> Revert change to type of tokenType

.github/workflows/imperative.yml, .github/workflows/linter.yml
=> Run on pull request as well as push

.github/workflows/imperative.yml, .github/workflows/linter.yml
When [ci skip] is in the latest commit message, do not run the test suites
=> Skip actions on ci skip

CHANGELOG.md, __tests__/__integration__/cmd/src/cli/validate/syntax/Syntax.definition.ts, __tests__/src/packages/cmd/SyntaxValidator.integration.test.ts, __tests__/src/packages/cmd/ValidationTestCommand.ts, packages/cmd/src/doc/option/ICommandOptionDefinition.ts, packages/cmd/src/syntax/SyntaxValidator.ts, packages/cmd/src/syntax/__tests__/SyntaxValidator.test.ts
=> Add arrayAllowDuplicate option

Jenkinsfile, sonar-project.properties
=> Update Jenkins agent to fix Sonar scan

Jenkinsfile, package-lock.json, package.json
Not sure why the Imperative pipeline's Check Vulnerability stage didn't catch this, but Zowe CLI did 🤔
=> Update pacote package to fix vulnerability

CHANGELOG.md, packages/rest/__tests__/client/__snapshots__/AbstractRestClient.test.ts.snap, packages/rest/src/client/AbstractRestClient.ts, packages/rest/src/client/doc/IRestClientError.ts
We may not need to merge this PR since the same functionality is already in master.
Please review and once it's 👍, will enable versioning and publishing from this branch 😋
=> Show protocol in error

CHANGELOG.md, Jenkinsfile, package.json, packages/rest/__tests__/client/AbstractRestClient.test.ts, packages/rest/src/client/AbstractRestClient.ts
=> Add decode option for REST client

packages/config/__tests__/ProfileInfo.test.ts, packages/config/__tests__/__resources__/ProfInfoApp_team_config_proj/ProfInfoApp.config.json, packages/config/__tests__/__resources__/ProfInfoApp_team_config_proj/ProfInfoApp.schema.json, packages/config/src/ProfileInfo.ts, packages/config/src/doc/IProfArgAttrs.ts, packages/utilities/src/CliUtils.ts
- Allow reading and overriding of missing arguments
=> Read environment Variables for ProfInfo APIs

CHANGELOG.md, __tests__/src/packages/utils/TextUtils.test.ts, __tests__/src/packages/utils/__snapshots__/TextUtils.test.ts.snap, package-lock.json, package.json, packages/cmd/__tests__/response/CommandResponse.test.ts, packages/cmd/__tests__/response/__snapshots__/CommandResponse.test.ts.snap, packages/cmd/src/response/CommandResponse.ts, packages/utilities/src/ImperativeConfig.ts, packages/utilities/src/TextUtils.ts
=> Update ProfInfo-for-next with master

.github/workflows/imperative.yml, package-lock.json, package.json
Kudos to @t1m0thyj and @awharn
=> Node 16 master

CHANGELOG.md, package-lock.json, packages/cmd/src/doc/response/api/handler/IHandlerResponseDataApi.ts
Resolves [https://github.com/zowe/zowe-cli/issues/663](url)
=> 663 - Added setMessage 'values' parameter usage documentation

CHANGELOG.md, __tests__/__integration__/imperative/__tests__/__integration__/cli/config/__resources__/expectedObjects.ts, packages/config/__tests__/ConfigSchema.test.ts, packages/config/__tests__/__resources__/ProfInfoApp_team_config_proj/ProfInfoApp.schema.json, packages/config/__tests__/__snapshots__/ConfigSchema.test.ts.snap, packages/config/src/ConfigSchema.ts, packages/imperative/__tests__/config/cmd/schema/schema.handler.test.ts
- Fix #624 
- Update draft + fix breaking changes between draft versions
=> Update Draft to Dec 2020

CHANGELOG.md, packages/imperative/src/config/cmd/init/init.definition.ts, packages/imperative/src/config/cmd/list/list.definition.ts, packages/imperative/src/config/cmd/profiles/profiles.definition.ts, packages/imperative/src/config/cmd/schema/schema.definition.ts, packages/imperative/src/config/cmd/secure/secure.definition.ts, packages/imperative/src/config/cmd/set/set.definition.ts
Resolves https://github.com/zowe/zowe-cli/issues/1061
=> Add `zowe config` group examples in Help

CHANGELOG.md, packages/config/__tests__/ConfigAutoStore.test.ts, packages/config/src/ConfigAutoStore.ts
=> [next] Fix auto-storing secure properties in plain text

.github/workflows/imperative.yml, CHANGELOG.md, package-lock.json, package.json
=> Update packages because of `colors`

CHANGELOG.md, packages/rest/__tests__/client/AbstractRestClient.test.ts, packages/rest/__tests__/client/__snapshots__/AbstractRestClient.test.ts.snap, packages/rest/src/client/AbstractRestClient.ts, packages/rest/src/client/CompressionUtils.ts
=> Update next with master

CHANGELOG.md, packages/cmd/__tests__/utils/CommandUtils.test.ts, packages/cmd/__tests__/utils/__snapshots__/CommandUtils.test.ts.snap, packages/cmd/src/utils/CommandUtils.ts
=> Be more specific when trying to match commands

CHANGELOG.md, packages/config/src/Config.ts, packages/config/src/ConfigAutoStore.ts, packages/config/src/api/ConfigSecure.ts, packages/imperative/src/auth/handlers/BaseAuthHandler.ts, packages/imperative/src/config/cmd/auto-init/handlers/BaseAutoInitHandler.ts, packages/imperative/src/config/cmd/convert-profiles/convert-profiles.handler.ts, packages/imperative/src/config/cmd/init/init.handler.ts, packages/imperative/src/config/cmd/secure/secure.handler.ts, packages/imperative/src/config/cmd/set/set.handler.ts
⚠️ Do not merge until #735 has been merged and published as a separate version
Resolves #732
=> [next] Only save active config layer by default

.github/workflows/imperative.yml, CHANGELOG.md, package-lock.json, package.json, packages/imperative/__tests__/plugins/cmd/list/__snapshots__/list.handler.test.ts.snap, packages/imperative/__tests__/plugins/cmd/list/list.handler.test.ts, packages/imperative/src/plugins/cmd/list/list.definition.ts, packages/imperative/src/plugins/cmd/list/list.handler.ts
=> Enhancements to plugins list command

CHANGELOG.md, package-lock.json, package.json
=> [next] Update moment

package-lock.json
=> [next] Update dev dependencies

package-lock.json
=> [v1] Update dev dependencies

.github/workflows/imperative.yml, CHANGELOG.md, gulp/TestTasks.ts, packages/utilities/__tests__/CliUtils.test.ts, packages/utilities/src/CliUtils.ts
In this PR:
- Port #768 
I recommend reviewing with whitespaces hidden 😋 
https://github.com/zowe/imperative/pull/801/files?w=1
=> Port #768 back to v1-lts

CHANGELOG.md, packages/imperative/__tests__/plugins/cmd/uninstall/uninstall.handler.test.ts, packages/imperative/__tests__/plugins/utilities/npm-interface/uninstall.test.ts, packages/imperative/src/plugins/cmd/uninstall/uninstall.handler.ts, packages/imperative/src/plugins/utilities/npm-interface/uninstall.ts
=> [v1] Fix plugin uninstall failing when there is space in path

.github/workflows/imperative.yml, CHANGELOG.md, package-lock.json, package.json, packages/utilities/__tests__/CliUtils.test.ts
* Update `cli-table3` dependency as requested in https://github.com/zowe/imperative/issues/764#issuecomment-1122121660
* Drop Node 12 (EoL) from our CI matrix and replace it with Node 18
=> Update cli-table3 and add Node 18 to CI

.github/workflows/imperative.yml
=> Quick fix for an NPM regression/issue

CHANGELOG.md, packages/cmd/__tests__/yargs/YargsConfigurer.test.ts, packages/cmd/src/yargs/YargsConfigurer.ts, packages/imperative/__tests__/handlers/__snapshots__/DefaultRootCommandHandler.test.ts.snap, packages/imperative/src/handlers/DefaultRootCommandHandler.ts
=> Fix `--response-format-json` issues in daemon mode

.github/workflows/imperative.yml, CHANGELOG.md, packages/cmd/__tests__/help/WebHelpGenerator.test.ts, packages/cmd/src/help/WebHelpGenerator.ts
Ports #872 and #873 to zowe-v1-lts
=> v1: Fix automatic link detection in web help

packages/cmd/src/profiles/CliProfileManager.ts, packages/cmd/src/response/CommandResponse.ts, packages/config/src/ConfigAutoStore.ts, packages/config/src/ConfigSchema.ts, packages/config/src/ProfileInfo.ts, packages/imperative/src/auth/handlers/BaseAuthHandler.ts, packages/utilities/__tests__/diff/WebDiffManager.test.ts
Fixes some code smells in Imperative
=> Fix code smells

README.md
=> Remove unusual install command in README

CHANGELOG.md, package-lock.json, package.json, packages/imperative/__tests__/plugins/cmd/install/install.handler.test.ts, packages/imperative/__tests__/plugins/cmd/uninstall/uninstall.handler.test.ts, packages/imperative/__tests__/plugins/cmd/update/update.handler.test.ts, packages/imperative/__tests__/plugins/utilities/npm-interface/install.test.ts, packages/imperative/__tests__/plugins/utilities/npm-interface/uninstall.test.ts, packages/imperative/__tests__/plugins/utilities/npm-interface/update.test.ts, packages/imperative/__tests__/plugins/utilities/runValidatePlugin.test.ts, packages/imperative/src/plugins/cmd/install/install.definition.ts, packages/imperative/src/plugins/cmd/update/update.definition.ts, packages/imperative/src/plugins/utilities/NpmFunctions.ts, packages/imperative/src/plugins/utilities/npm-interface/uninstall.ts, packages/imperative/src/plugins/utilities/runValidatePlugin.ts
Implements #900 and #901 in v2-lts
=> Port V1 updates to V2

.github/workflows/imperative.yml, .github/workflows/sonar.yml
Same changes as https://github.com/zowe/zowe-cli/pull/1567 for the Imperative repo
=> Fix Sonar scan not running for fork PRs

.github/workflows/imperative.yml, package-lock.json
...because the new Sonar workflow added in #904 applies to all branches.
=> [v1] Remove duplicate Sonar scan and update deps

packages/cmd/src/help/WebHelpGenerator.ts
=> [v1] Optimize slow regexes detected by SonarCloud

doc/Architecture.md, doc/Plugin Architecture/Plugin Development.md, packages/profiles/src/validation/doc/IProfileValidationTaskResult.ts
=> Remove outdated links and update typedoc

CHANGELOG.md, packages/index.ts
=> Exported `AppSettings` for CLI and other Apps to use

CHANGELOG.md, packages/imperative/index.ts
=> Exported the IAuthHandlerApi from imperative package

CHANGELOG.md, __tests__/src/packages/imperative/plugins/suites/ValidatePlugin.ts, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/index.d.ts, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/index.js, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/index.js.map, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/cmd/bar/bar.handler.d.ts, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/cmd/bar/bar.handler.js, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/cmd/bar/bar.handler.js.map, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/cmd/foo/foo.handler.d.ts, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/cmd/foo/foo.handler.js, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/cmd/foo/foo.handler.js.map, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/healthCheck.handler.d.ts, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/healthCheck.handler.js, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/healthCheck.handler.js.map, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/index.d.ts, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/index.js, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/lib/sample-plugin/index.js.map, __tests__/src/packages/imperative/plugins/test_plugins/chained_handler_plugin/package.json, __tests__/src/packages/imperative/plugins/test_plugins/error_plugins/definition_bad_chained_handler/dummy.handler.js, __tests__/src/packages/imperative/plugins/test_plugins/error_plugins/definition_bad_chained_handler/package.json, __tests__/src/packages/imperative/plugins/test_plugins/error_plugins/definition_empty_chained_handler/dummy.handler.js, __tests__/src/packages/imperative/plugins/test_plugins/error_plugins/definition_empty_chained_handler/package.json, __tests__/src/packages/imperative/plugins/test_plugins/error_plugins/definition_missing_chained_handler/dummy.handler.js, __tests__/src/packages/imperative/plugins/test_plugins/error_plugins/definition_missing_chained_handler/package.json, packages/imperative/__tests__/plugins/PluginManagementFacility.test.ts, packages/imperative/src/plugins/PluginManagementFacility.ts
Fixes #320 in V1
Updates plugin validation logic to fix a situation where plugin commands with chained command handlers would fail plugin validation.
=> Fix chained handler validation - v1-lts

CHANGELOG.md, packages/io/__tests__/IO.test.ts, packages/io/src/IO.ts
=> [v1] Fix IO.writeFileAsync method throwing errors badly

CHANGELOG.md, packages/cmd/__tests__/CommandProcessor.test.ts, packages/cmd/src/CommandProcessor.ts
=> Fix npm not found on zowe plugins install

CHANGELOG.md, __tests__/__integration__/cmd/__tests__/integration/cli/invoke/Cmd.cli.invoke.test.ts, __tests__/__integration__/cmd/__tests__/integration/cli/invoke/__scripts__/invoke_help_examples.sh, __tests__/__integration__/cmd/__tests__/integration/cli/invoke/__snapshots__/Cmd.cli.invoke.test.ts.snap, package-lock.json, packages/cmd/src/yargs/GroupCommandYargs.ts
=> Fix help-examples option failing on command groups

CHANGELOG.md, __tests__/__integration__/imperative/__tests__/__integration__/cli/config/report-env/cli.imperative-test-cli.config.report-env.integration.test.ts, __tests__/src/packages/imperative/plugins/test_cli/node_modules/@zowe/imperative, packages/imperative/__tests__/Imperative.test.ts, packages/imperative/src/Imperative.ts, packages/utilities/__tests__/EnvFileUtils.test.ts, packages/utilities/index.ts, packages/utilities/src/EnvFileUtils.ts
Implements the basic initial implementation of the environment configuration file.
Adds unit and integration tests for the new SDK and behavior.
This PR makes a slight modification to the Imperative initialization order. It is not believed that this change will impact any consumers of the CLI or Imperative, and all tests continue to pass.
=> Implement environment config files

CHANGELOG.md, packages/cmd/__tests__/CommandProcessor.test.ts, packages/cmd/__tests__/__resources__/.zowe.env.json, packages/cmd/__tests__/__snapshots__/CommandProcessor.test.ts.snap, packages/cmd/src/CommandProcessor.ts, packages/utilities/src/EnvFileUtils.ts
Fixes behavior where, in daemon mode, the daemon client's provided environment variables override and clobber the environment variables set from the environment file.
=> Fix environment files defect in daemon mode

CHANGELOG.md, __tests__/__integration__/cmd/__tests__/integration/cli/auth/Cmd.cli.auth.login.fruit.integration.test.ts, __tests__/__integration__/cmd/__tests__/integration/cli/auth/Cmd.cli.auth.logout.fruit.integration.test.ts, __tests__/__integration__/cmd/__tests__/integration/cli/auth/__scripts__/base_profile_and_auth_li.sh, __tests__/__integration__/cmd/__tests__/integration/cli/auth/__scripts__/base_profile_and_auth_lo.sh, packages/constants/src/Constants.ts, packages/imperative/src/auth/handlers/BaseAuthHandler.ts
=> Fix the auth group aliases (v1)

CHANGELOG.md, __tests__/__integration__/cmd/__tests__/integration/cli/auth/Cmd.cli.auth.login.fruit.integration.test.ts, __tests__/__integration__/cmd/__tests__/integration/cli/auth/Cmd.cli.auth.logout.fruit.integration.test.ts, __tests__/__integration__/cmd/__tests__/integration/cli/auth/__scripts__/base_profile_and_auth_li.sh, __tests__/__integration__/cmd/__tests__/integration/cli/auth/__scripts__/base_profile_and_auth_lo.sh, packages/constants/src/Constants.ts, packages/imperative/src/auth/handlers/AbstractAuthHandler.ts
=> Fix the auth group aliases

README.md
Explicitly tell visitors of the repository how they can report bugs or request enhancements. OpenSSF requirement: "The project website MUST provide information on how to: obtain, provide feedback (as bug reports or enhancements), and contribute to the software."
=> Changes to achieve OpenSSF Passing badge

README.md
This PR adds the OpenSSF Best Practices Passing badge to Readme.md.
=> Add OpenSSF Best Practices Passing badge

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/label-actions.yml, .github/workflows/auto-comment.yml, .github/workflows/imperative.yml, .github/workflows/sonar.yml, .github/workflows/stale.yml
Action | Description
-- | --
#1 | add [stale bot](https://github.com/zowe/zowe-cli/blob/master/.github/workflows/stale.yml)	
#2 | add [auto-comment](https://github.com/zowe/zowe-cli/blob/master/.github/workflows/auto-comment.yml) bot [on labels](https://github.com/zowe/zowe-cli/blob/master/.github/label-actions.yml)										
#3 | add issue template ([Bug](https://github.com/zowe/zowe-cli/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), [Feature](https://github.com/zowe/zowe-cli/blob/master/.github/ISSUE_TEMPLATE/feature_request.md))										
#4 | add [PR Template ](https://docs.google.com/document/u/0/d/1BvA8zNQs6QP1_gHJw7XsbEGNTTCH-v0SjM4kwMym3Cw/edit)   										
#5 | add [question redirect](https://github.com/zowe/zowe-cli/blob/master/.github/ISSUE_TEMPLATE/config.yml) …
=> Update workflows - master

.github/workflows/audit.yml, .github/workflows/changelog.yml, .github/workflows/imperative.yml, .github/workflows/linter.yml
Action | Description
-- | --									
#6 | [update all workflows to remove deprecation warnings](https://github.com/zowe/zowe-cli-web-help-generator/pull/35/files), [octorelease updates](https://github.com/zowe/zowe-cli/pull/1712)										
#7 | remove Node 14 from workflow matrix
=> updated workflows - lts

CHANGELOG.md
Fixes mismatched issue numbers/links for previous releases.
=> chore: Update changelog issue #s
